/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the CreateSandboxDepositResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSandboxDepositResponse{}

// CreateSandboxDepositResponse struct for CreateSandboxDepositResponse
type CreateSandboxDepositResponse struct {
	// The UUID of the customer activity created for the deposit.
	ActivityId *string `json:"activity_id,omitempty"`
}

// NewCreateSandboxDepositResponse instantiates a new CreateSandboxDepositResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSandboxDepositResponse() *CreateSandboxDepositResponse {
	this := CreateSandboxDepositResponse{}
	return &this
}

// NewCreateSandboxDepositResponseWithDefaults instantiates a new CreateSandboxDepositResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSandboxDepositResponseWithDefaults() *CreateSandboxDepositResponse {
	this := CreateSandboxDepositResponse{}
	return &this
}

// GetActivityId returns the ActivityId field value if set, zero value otherwise.
func (o *CreateSandboxDepositResponse) GetActivityId() string {
	if o == nil || IsNil(o.ActivityId) {
		var ret string
		return ret
	}
	return *o.ActivityId
}

// GetActivityIdOk returns a tuple with the ActivityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSandboxDepositResponse) GetActivityIdOk() (*string, bool) {
	if o == nil || IsNil(o.ActivityId) {
		return nil, false
	}
	return o.ActivityId, true
}

// HasActivityId returns a boolean if a field has been set.
func (o *CreateSandboxDepositResponse) HasActivityId() bool {
	if o != nil && !IsNil(o.ActivityId) {
		return true
	}

	return false
}

// SetActivityId gets a reference to the given string and assigns it to the ActivityId field.
func (o *CreateSandboxDepositResponse) SetActivityId(v string) {
	o.ActivityId = &v
}

func (o CreateSandboxDepositResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSandboxDepositResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActivityId) {
		toSerialize["activity_id"] = o.ActivityId
	}
	return toSerialize, nil
}

type NullableCreateSandboxDepositResponse struct {
	value *CreateSandboxDepositResponse
	isSet bool
}

func (v NullableCreateSandboxDepositResponse) Get() *CreateSandboxDepositResponse {
	return v.value
}

func (v *NullableCreateSandboxDepositResponse) Set(val *CreateSandboxDepositResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSandboxDepositResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSandboxDepositResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSandboxDepositResponse(val *CreateSandboxDepositResponse) *NullableCreateSandboxDepositResponse {
	return &NullableCreateSandboxDepositResponse{value: val, isSet: true}
}

func (v NullableCreateSandboxDepositResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSandboxDepositResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


