/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WireRoutingDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WireRoutingDetails{}

// WireRoutingDetails struct for WireRoutingDetails
type WireRoutingDetails struct {
	RoutingNumberType FiatWireAccountType `json:"routing_number_type"`
	// The routing number.
	RoutingNumber string `json:"routing_number"`
	// The name of the bank.
	BankName string `json:"bank_name"`
	BankAddress MailingAddress `json:"bank_address"`
}

type _WireRoutingDetails WireRoutingDetails

// NewWireRoutingDetails instantiates a new WireRoutingDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWireRoutingDetails(routingNumberType FiatWireAccountType, routingNumber string, bankName string, bankAddress MailingAddress) *WireRoutingDetails {
	this := WireRoutingDetails{}
	this.RoutingNumberType = routingNumberType
	this.RoutingNumber = routingNumber
	this.BankName = bankName
	this.BankAddress = bankAddress
	return &this
}

// NewWireRoutingDetailsWithDefaults instantiates a new WireRoutingDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWireRoutingDetailsWithDefaults() *WireRoutingDetails {
	this := WireRoutingDetails{}
	return &this
}

// GetRoutingNumberType returns the RoutingNumberType field value
func (o *WireRoutingDetails) GetRoutingNumberType() FiatWireAccountType {
	if o == nil {
		var ret FiatWireAccountType
		return ret
	}

	return o.RoutingNumberType
}

// GetRoutingNumberTypeOk returns a tuple with the RoutingNumberType field value
// and a boolean to check if the value has been set.
func (o *WireRoutingDetails) GetRoutingNumberTypeOk() (*FiatWireAccountType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoutingNumberType, true
}

// SetRoutingNumberType sets field value
func (o *WireRoutingDetails) SetRoutingNumberType(v FiatWireAccountType) {
	o.RoutingNumberType = v
}

// GetRoutingNumber returns the RoutingNumber field value
func (o *WireRoutingDetails) GetRoutingNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoutingNumber
}

// GetRoutingNumberOk returns a tuple with the RoutingNumber field value
// and a boolean to check if the value has been set.
func (o *WireRoutingDetails) GetRoutingNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoutingNumber, true
}

// SetRoutingNumber sets field value
func (o *WireRoutingDetails) SetRoutingNumber(v string) {
	o.RoutingNumber = v
}

// GetBankName returns the BankName field value
func (o *WireRoutingDetails) GetBankName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankName
}

// GetBankNameOk returns a tuple with the BankName field value
// and a boolean to check if the value has been set.
func (o *WireRoutingDetails) GetBankNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankName, true
}

// SetBankName sets field value
func (o *WireRoutingDetails) SetBankName(v string) {
	o.BankName = v
}

// GetBankAddress returns the BankAddress field value
func (o *WireRoutingDetails) GetBankAddress() MailingAddress {
	if o == nil {
		var ret MailingAddress
		return ret
	}

	return o.BankAddress
}

// GetBankAddressOk returns a tuple with the BankAddress field value
// and a boolean to check if the value has been set.
func (o *WireRoutingDetails) GetBankAddressOk() (*MailingAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankAddress, true
}

// SetBankAddress sets field value
func (o *WireRoutingDetails) SetBankAddress(v MailingAddress) {
	o.BankAddress = v
}

func (o WireRoutingDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WireRoutingDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["routing_number_type"] = o.RoutingNumberType
	toSerialize["routing_number"] = o.RoutingNumber
	toSerialize["bank_name"] = o.BankName
	toSerialize["bank_address"] = o.BankAddress
	return toSerialize, nil
}

func (o *WireRoutingDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"routing_number_type",
		"routing_number",
		"bank_name",
		"bank_address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWireRoutingDetails := _WireRoutingDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWireRoutingDetails)

	if err != nil {
		return err
	}

	*o = WireRoutingDetails(varWireRoutingDetails)

	return err
}

type NullableWireRoutingDetails struct {
	value *WireRoutingDetails
	isSet bool
}

func (v NullableWireRoutingDetails) Get() *WireRoutingDetails {
	return v.value
}

func (v *NullableWireRoutingDetails) Set(val *WireRoutingDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableWireRoutingDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableWireRoutingDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWireRoutingDetails(val *WireRoutingDetails) *NullableWireRoutingDetails {
	return &NullableWireRoutingDetails{value: val, isSet: true}
}

func (v NullableWireRoutingDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWireRoutingDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


