/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the ListIssuerQuoteExecutionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIssuerQuoteExecutionsResponse{}

// ListIssuerQuoteExecutionsResponse struct for ListIssuerQuoteExecutionsResponse
type ListIssuerQuoteExecutionsResponse struct {
	IssuerQuoteExecutions []IssuerQuoteExecution `json:"issuer_quote_executions,omitempty"`
	NextPageCursor *string `json:"next_page_cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListIssuerQuoteExecutionsResponse ListIssuerQuoteExecutionsResponse

// NewListIssuerQuoteExecutionsResponse instantiates a new ListIssuerQuoteExecutionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIssuerQuoteExecutionsResponse() *ListIssuerQuoteExecutionsResponse {
	this := ListIssuerQuoteExecutionsResponse{}
	return &this
}

// NewListIssuerQuoteExecutionsResponseWithDefaults instantiates a new ListIssuerQuoteExecutionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIssuerQuoteExecutionsResponseWithDefaults() *ListIssuerQuoteExecutionsResponse {
	this := ListIssuerQuoteExecutionsResponse{}
	return &this
}

// GetIssuerQuoteExecutions returns the IssuerQuoteExecutions field value if set, zero value otherwise.
func (o *ListIssuerQuoteExecutionsResponse) GetIssuerQuoteExecutions() []IssuerQuoteExecution {
	if o == nil || IsNil(o.IssuerQuoteExecutions) {
		var ret []IssuerQuoteExecution
		return ret
	}
	return o.IssuerQuoteExecutions
}

// GetIssuerQuoteExecutionsOk returns a tuple with the IssuerQuoteExecutions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListIssuerQuoteExecutionsResponse) GetIssuerQuoteExecutionsOk() ([]IssuerQuoteExecution, bool) {
	if o == nil || IsNil(o.IssuerQuoteExecutions) {
		return nil, false
	}
	return o.IssuerQuoteExecutions, true
}

// HasIssuerQuoteExecutions returns a boolean if a field has been set.
func (o *ListIssuerQuoteExecutionsResponse) HasIssuerQuoteExecutions() bool {
	if o != nil && !IsNil(o.IssuerQuoteExecutions) {
		return true
	}

	return false
}

// SetIssuerQuoteExecutions gets a reference to the given []IssuerQuoteExecution and assigns it to the IssuerQuoteExecutions field.
func (o *ListIssuerQuoteExecutionsResponse) SetIssuerQuoteExecutions(v []IssuerQuoteExecution) {
	o.IssuerQuoteExecutions = v
}

// GetNextPageCursor returns the NextPageCursor field value if set, zero value otherwise.
func (o *ListIssuerQuoteExecutionsResponse) GetNextPageCursor() string {
	if o == nil || IsNil(o.NextPageCursor) {
		var ret string
		return ret
	}
	return *o.NextPageCursor
}

// GetNextPageCursorOk returns a tuple with the NextPageCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListIssuerQuoteExecutionsResponse) GetNextPageCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageCursor) {
		return nil, false
	}
	return o.NextPageCursor, true
}

// HasNextPageCursor returns a boolean if a field has been set.
func (o *ListIssuerQuoteExecutionsResponse) HasNextPageCursor() bool {
	if o != nil && !IsNil(o.NextPageCursor) {
		return true
	}

	return false
}

// SetNextPageCursor gets a reference to the given string and assigns it to the NextPageCursor field.
func (o *ListIssuerQuoteExecutionsResponse) SetNextPageCursor(v string) {
	o.NextPageCursor = &v
}

func (o ListIssuerQuoteExecutionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIssuerQuoteExecutionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IssuerQuoteExecutions) {
		toSerialize["issuer_quote_executions"] = o.IssuerQuoteExecutions
	}
	if !IsNil(o.NextPageCursor) {
		toSerialize["next_page_cursor"] = o.NextPageCursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListIssuerQuoteExecutionsResponse) UnmarshalJSON(data []byte) (err error) {
	varListIssuerQuoteExecutionsResponse := _ListIssuerQuoteExecutionsResponse{}

	err = json.Unmarshal(data, &varListIssuerQuoteExecutionsResponse)

	if err != nil {
		return err
	}

	*o = ListIssuerQuoteExecutionsResponse(varListIssuerQuoteExecutionsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "issuer_quote_executions")
		delete(additionalProperties, "next_page_cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListIssuerQuoteExecutionsResponse struct {
	value *ListIssuerQuoteExecutionsResponse
	isSet bool
}

func (v NullableListIssuerQuoteExecutionsResponse) Get() *ListIssuerQuoteExecutionsResponse {
	return v.value
}

func (v *NullableListIssuerQuoteExecutionsResponse) Set(val *ListIssuerQuoteExecutionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListIssuerQuoteExecutionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListIssuerQuoteExecutionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIssuerQuoteExecutionsResponse(val *ListIssuerQuoteExecutionsResponse) *NullableListIssuerQuoteExecutionsResponse {
	return &NullableListIssuerQuoteExecutionsResponse{value: val, isSet: true}
}

func (v NullableListIssuerQuoteExecutionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIssuerQuoteExecutionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


