/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the OrchestrationProfileSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrchestrationProfileSource{}

// OrchestrationProfileSource struct for OrchestrationProfileSource
type OrchestrationProfileSource struct {
	ProfileId *string `json:"profile_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrchestrationProfileSource OrchestrationProfileSource

// NewOrchestrationProfileSource instantiates a new OrchestrationProfileSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrchestrationProfileSource() *OrchestrationProfileSource {
	this := OrchestrationProfileSource{}
	return &this
}

// NewOrchestrationProfileSourceWithDefaults instantiates a new OrchestrationProfileSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrchestrationProfileSourceWithDefaults() *OrchestrationProfileSource {
	this := OrchestrationProfileSource{}
	return &this
}

// GetProfileId returns the ProfileId field value if set, zero value otherwise.
func (o *OrchestrationProfileSource) GetProfileId() string {
	if o == nil || IsNil(o.ProfileId) {
		var ret string
		return ret
	}
	return *o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrchestrationProfileSource) GetProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProfileId) {
		return nil, false
	}
	return o.ProfileId, true
}

// HasProfileId returns a boolean if a field has been set.
func (o *OrchestrationProfileSource) HasProfileId() bool {
	if o != nil && !IsNil(o.ProfileId) {
		return true
	}

	return false
}

// SetProfileId gets a reference to the given string and assigns it to the ProfileId field.
func (o *OrchestrationProfileSource) SetProfileId(v string) {
	o.ProfileId = &v
}

func (o OrchestrationProfileSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrchestrationProfileSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProfileId) {
		toSerialize["profile_id"] = o.ProfileId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrchestrationProfileSource) UnmarshalJSON(data []byte) (err error) {
	varOrchestrationProfileSource := _OrchestrationProfileSource{}

	err = json.Unmarshal(data, &varOrchestrationProfileSource)

	if err != nil {
		return err
	}

	*o = OrchestrationProfileSource(varOrchestrationProfileSource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "profile_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrchestrationProfileSource struct {
	value *OrchestrationProfileSource
	isSet bool
}

func (v NullableOrchestrationProfileSource) Get() *OrchestrationProfileSource {
	return v.value
}

func (v *NullableOrchestrationProfileSource) Set(val *OrchestrationProfileSource) {
	v.value = val
	v.isSet = true
}

func (v NullableOrchestrationProfileSource) IsSet() bool {
	return v.isSet
}

func (v *NullableOrchestrationProfileSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrchestrationProfileSource(val *OrchestrationProfileSource) *NullableOrchestrationProfileSource {
	return &NullableOrchestrationProfileSource{value: val, isSet: true}
}

func (v NullableOrchestrationProfileSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrchestrationProfileSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


