/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the CreateOrchestrationRequestCryptoDestination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrchestrationRequestCryptoDestination{}

// CreateOrchestrationRequestCryptoDestination struct for CreateOrchestrationRequestCryptoDestination
type CreateOrchestrationRequestCryptoDestination struct {
	// The ID of a pre-approved crypto destination address.  Valid crypto addresses can be retrieved using: - ListCryptoDestinationAddresses endpoint (/transfer/crypto-destination-addresses) - PutCryptoDestinationAddress endpoint (/transfer/crypto-destination-address)
	AddressId *string `json:"address_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateOrchestrationRequestCryptoDestination CreateOrchestrationRequestCryptoDestination

// NewCreateOrchestrationRequestCryptoDestination instantiates a new CreateOrchestrationRequestCryptoDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrchestrationRequestCryptoDestination() *CreateOrchestrationRequestCryptoDestination {
	this := CreateOrchestrationRequestCryptoDestination{}
	return &this
}

// NewCreateOrchestrationRequestCryptoDestinationWithDefaults instantiates a new CreateOrchestrationRequestCryptoDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrchestrationRequestCryptoDestinationWithDefaults() *CreateOrchestrationRequestCryptoDestination {
	this := CreateOrchestrationRequestCryptoDestination{}
	return &this
}

// GetAddressId returns the AddressId field value if set, zero value otherwise.
func (o *CreateOrchestrationRequestCryptoDestination) GetAddressId() string {
	if o == nil || IsNil(o.AddressId) {
		var ret string
		return ret
	}
	return *o.AddressId
}

// GetAddressIdOk returns a tuple with the AddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrchestrationRequestCryptoDestination) GetAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.AddressId) {
		return nil, false
	}
	return o.AddressId, true
}

// HasAddressId returns a boolean if a field has been set.
func (o *CreateOrchestrationRequestCryptoDestination) HasAddressId() bool {
	if o != nil && !IsNil(o.AddressId) {
		return true
	}

	return false
}

// SetAddressId gets a reference to the given string and assigns it to the AddressId field.
func (o *CreateOrchestrationRequestCryptoDestination) SetAddressId(v string) {
	o.AddressId = &v
}

func (o CreateOrchestrationRequestCryptoDestination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrchestrationRequestCryptoDestination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddressId) {
		toSerialize["address_id"] = o.AddressId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOrchestrationRequestCryptoDestination) UnmarshalJSON(data []byte) (err error) {
	varCreateOrchestrationRequestCryptoDestination := _CreateOrchestrationRequestCryptoDestination{}

	err = json.Unmarshal(data, &varCreateOrchestrationRequestCryptoDestination)

	if err != nil {
		return err
	}

	*o = CreateOrchestrationRequestCryptoDestination(varCreateOrchestrationRequestCryptoDestination)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOrchestrationRequestCryptoDestination struct {
	value *CreateOrchestrationRequestCryptoDestination
	isSet bool
}

func (v NullableCreateOrchestrationRequestCryptoDestination) Get() *CreateOrchestrationRequestCryptoDestination {
	return v.value
}

func (v *NullableCreateOrchestrationRequestCryptoDestination) Set(val *CreateOrchestrationRequestCryptoDestination) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrchestrationRequestCryptoDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrchestrationRequestCryptoDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrchestrationRequestCryptoDestination(val *CreateOrchestrationRequestCryptoDestination) *NullableCreateOrchestrationRequestCryptoDestination {
	return &NullableCreateOrchestrationRequestCryptoDestination{value: val, isSet: true}
}

func (v NullableCreateOrchestrationRequestCryptoDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrchestrationRequestCryptoDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


