/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the UpdateFiatAccountRequestUpdateFiatNetworkInstructions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateFiatAccountRequestUpdateFiatNetworkInstructions{}

// UpdateFiatAccountRequestUpdateFiatNetworkInstructions struct for UpdateFiatAccountRequestUpdateFiatNetworkInstructions
type UpdateFiatAccountRequestUpdateFiatNetworkInstructions struct {
	Wire *UpdateFiatNetworkInstructionsUpdateWire `json:"wire,omitempty"`
}

// NewUpdateFiatAccountRequestUpdateFiatNetworkInstructions instantiates a new UpdateFiatAccountRequestUpdateFiatNetworkInstructions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateFiatAccountRequestUpdateFiatNetworkInstructions() *UpdateFiatAccountRequestUpdateFiatNetworkInstructions {
	this := UpdateFiatAccountRequestUpdateFiatNetworkInstructions{}
	return &this
}

// NewUpdateFiatAccountRequestUpdateFiatNetworkInstructionsWithDefaults instantiates a new UpdateFiatAccountRequestUpdateFiatNetworkInstructions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateFiatAccountRequestUpdateFiatNetworkInstructionsWithDefaults() *UpdateFiatAccountRequestUpdateFiatNetworkInstructions {
	this := UpdateFiatAccountRequestUpdateFiatNetworkInstructions{}
	return &this
}

// GetWire returns the Wire field value if set, zero value otherwise.
func (o *UpdateFiatAccountRequestUpdateFiatNetworkInstructions) GetWire() UpdateFiatNetworkInstructionsUpdateWire {
	if o == nil || IsNil(o.Wire) {
		var ret UpdateFiatNetworkInstructionsUpdateWire
		return ret
	}
	return *o.Wire
}

// GetWireOk returns a tuple with the Wire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateFiatAccountRequestUpdateFiatNetworkInstructions) GetWireOk() (*UpdateFiatNetworkInstructionsUpdateWire, bool) {
	if o == nil || IsNil(o.Wire) {
		return nil, false
	}
	return o.Wire, true
}

// HasWire returns a boolean if a field has been set.
func (o *UpdateFiatAccountRequestUpdateFiatNetworkInstructions) HasWire() bool {
	if o != nil && !IsNil(o.Wire) {
		return true
	}

	return false
}

// SetWire gets a reference to the given UpdateFiatNetworkInstructionsUpdateWire and assigns it to the Wire field.
func (o *UpdateFiatAccountRequestUpdateFiatNetworkInstructions) SetWire(v UpdateFiatNetworkInstructionsUpdateWire) {
	o.Wire = &v
}

func (o UpdateFiatAccountRequestUpdateFiatNetworkInstructions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateFiatAccountRequestUpdateFiatNetworkInstructions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Wire) {
		toSerialize["wire"] = o.Wire
	}
	return toSerialize, nil
}

type NullableUpdateFiatAccountRequestUpdateFiatNetworkInstructions struct {
	value *UpdateFiatAccountRequestUpdateFiatNetworkInstructions
	isSet bool
}

func (v NullableUpdateFiatAccountRequestUpdateFiatNetworkInstructions) Get() *UpdateFiatAccountRequestUpdateFiatNetworkInstructions {
	return v.value
}

func (v *NullableUpdateFiatAccountRequestUpdateFiatNetworkInstructions) Set(val *UpdateFiatAccountRequestUpdateFiatNetworkInstructions) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFiatAccountRequestUpdateFiatNetworkInstructions) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFiatAccountRequestUpdateFiatNetworkInstructions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFiatAccountRequestUpdateFiatNetworkInstructions(val *UpdateFiatAccountRequestUpdateFiatNetworkInstructions) *NullableUpdateFiatAccountRequestUpdateFiatNetworkInstructions {
	return &NullableUpdateFiatAccountRequestUpdateFiatNetworkInstructions{value: val, isSet: true}
}

func (v NullableUpdateFiatAccountRequestUpdateFiatNetworkInstructions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFiatAccountRequestUpdateFiatNetworkInstructions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


