/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
	"fmt"
)

// checks if the AddAccountMembersRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAccountMembersRequest{}

// AddAccountMembersRequest struct for AddAccountMembersRequest
type AddAccountMembersRequest struct {
	// ID of account to which members will be added.
	AccountId string `json:"account_id"`
	// A non-empty array of account members to be added.
	Members []AccountMember `json:"members"`
	AdditionalProperties map[string]interface{}
}

type _AddAccountMembersRequest AddAccountMembersRequest

// NewAddAccountMembersRequest instantiates a new AddAccountMembersRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAccountMembersRequest(accountId string, members []AccountMember) *AddAccountMembersRequest {
	this := AddAccountMembersRequest{}
	this.AccountId = accountId
	this.Members = members
	return &this
}

// NewAddAccountMembersRequestWithDefaults instantiates a new AddAccountMembersRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAccountMembersRequestWithDefaults() *AddAccountMembersRequest {
	this := AddAccountMembersRequest{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *AddAccountMembersRequest) GetAccountId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *AddAccountMembersRequest) GetAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *AddAccountMembersRequest) SetAccountId(v string) {
	o.AccountId = v
}

// GetMembers returns the Members field value
func (o *AddAccountMembersRequest) GetMembers() []AccountMember {
	if o == nil {
		var ret []AccountMember
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *AddAccountMembersRequest) GetMembersOk() ([]AccountMember, bool) {
	if o == nil {
		return nil, false
	}
	return o.Members, true
}

// SetMembers sets field value
func (o *AddAccountMembersRequest) SetMembers(v []AccountMember) {
	o.Members = v
}

func (o AddAccountMembersRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAccountMembersRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["members"] = o.Members

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddAccountMembersRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"members",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddAccountMembersRequest := _AddAccountMembersRequest{}

	err = json.Unmarshal(data, &varAddAccountMembersRequest)

	if err != nil {
		return err
	}

	*o = AddAccountMembersRequest(varAddAccountMembersRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "members")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddAccountMembersRequest struct {
	value *AddAccountMembersRequest
	isSet bool
}

func (v NullableAddAccountMembersRequest) Get() *AddAccountMembersRequest {
	return v.value
}

func (v *NullableAddAccountMembersRequest) Set(val *AddAccountMembersRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAccountMembersRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAccountMembersRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAccountMembersRequest(val *AddAccountMembersRequest) *NullableAddAccountMembersRequest {
	return &NullableAddAccountMembersRequest{value: val, isSet: true}
}

func (v NullableAddAccountMembersRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAccountMembersRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


