/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
	"time"
)

// checks if the Orchestration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Orchestration{}

// Orchestration Orchestrations can be created directly via the CreateOrchestration endpoint, or indirectly by an incoming deposit which matches an OrchestrationRule previously defined with the CreateOrchestrationRule endpoint.
type Orchestration struct {
	Id *string `json:"id,omitempty"`
	ProfileId *string `json:"profile_id,omitempty"`
	IdentityId *string `json:"identity_id,omitempty"`
	AccountId *string `json:"account_id,omitempty"`
	CustomerId *string `json:"customer_id,omitempty"`
	// A client or system-specified unique identifier for the orchestration - used for idempotency protection. Retries of a request should use the same ref_id to avoid duplicate transactions. For system-initiated orchestrations generated by invocation of an orchestration rule, the ref_id is generated the system.
	RefId *string `json:"ref_id,omitempty"`
	SourceAsset *string `json:"source_asset,omitempty"`
	DestinationAsset *string `json:"destination_asset,omitempty"`
	SourceAmount *string `json:"source_amount,omitempty"`
	SourceTransfer *TransferDetails `json:"source_transfer,omitempty"`
	DestinationTransfer *TransferDetails `json:"destination_transfer,omitempty"`
	Status *OrchestrationStatus `json:"status,omitempty"`
	FailReason *FailReason `json:"fail_reason,omitempty"`
	Source *OrchestrationSource `json:"source,omitempty"`
	Destination *OrchestrationDestination `json:"destination,omitempty"`
	// The ID of the orchestration rule which triggered this orchestration. Can be empty for ad-hoc orchestrations.
	OrchestrationRuleId *string `json:"orchestration_rule_id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Orchestration Orchestration

// NewOrchestration instantiates a new Orchestration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrchestration() *Orchestration {
	this := Orchestration{}
	return &this
}

// NewOrchestrationWithDefaults instantiates a new Orchestration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrchestrationWithDefaults() *Orchestration {
	this := Orchestration{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Orchestration) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Orchestration) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Orchestration) SetId(v string) {
	o.Id = &v
}

// GetProfileId returns the ProfileId field value if set, zero value otherwise.
func (o *Orchestration) GetProfileId() string {
	if o == nil || IsNil(o.ProfileId) {
		var ret string
		return ret
	}
	return *o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProfileId) {
		return nil, false
	}
	return o.ProfileId, true
}

// HasProfileId returns a boolean if a field has been set.
func (o *Orchestration) HasProfileId() bool {
	if o != nil && !IsNil(o.ProfileId) {
		return true
	}

	return false
}

// SetProfileId gets a reference to the given string and assigns it to the ProfileId field.
func (o *Orchestration) SetProfileId(v string) {
	o.ProfileId = &v
}

// GetIdentityId returns the IdentityId field value if set, zero value otherwise.
func (o *Orchestration) GetIdentityId() string {
	if o == nil || IsNil(o.IdentityId) {
		var ret string
		return ret
	}
	return *o.IdentityId
}

// GetIdentityIdOk returns a tuple with the IdentityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetIdentityIdOk() (*string, bool) {
	if o == nil || IsNil(o.IdentityId) {
		return nil, false
	}
	return o.IdentityId, true
}

// HasIdentityId returns a boolean if a field has been set.
func (o *Orchestration) HasIdentityId() bool {
	if o != nil && !IsNil(o.IdentityId) {
		return true
	}

	return false
}

// SetIdentityId gets a reference to the given string and assigns it to the IdentityId field.
func (o *Orchestration) SetIdentityId(v string) {
	o.IdentityId = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *Orchestration) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *Orchestration) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *Orchestration) SetAccountId(v string) {
	o.AccountId = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *Orchestration) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *Orchestration) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *Orchestration) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetRefId returns the RefId field value if set, zero value otherwise.
func (o *Orchestration) GetRefId() string {
	if o == nil || IsNil(o.RefId) {
		var ret string
		return ret
	}
	return *o.RefId
}

// GetRefIdOk returns a tuple with the RefId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetRefIdOk() (*string, bool) {
	if o == nil || IsNil(o.RefId) {
		return nil, false
	}
	return o.RefId, true
}

// HasRefId returns a boolean if a field has been set.
func (o *Orchestration) HasRefId() bool {
	if o != nil && !IsNil(o.RefId) {
		return true
	}

	return false
}

// SetRefId gets a reference to the given string and assigns it to the RefId field.
func (o *Orchestration) SetRefId(v string) {
	o.RefId = &v
}

// GetSourceAsset returns the SourceAsset field value if set, zero value otherwise.
func (o *Orchestration) GetSourceAsset() string {
	if o == nil || IsNil(o.SourceAsset) {
		var ret string
		return ret
	}
	return *o.SourceAsset
}

// GetSourceAssetOk returns a tuple with the SourceAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetSourceAssetOk() (*string, bool) {
	if o == nil || IsNil(o.SourceAsset) {
		return nil, false
	}
	return o.SourceAsset, true
}

// HasSourceAsset returns a boolean if a field has been set.
func (o *Orchestration) HasSourceAsset() bool {
	if o != nil && !IsNil(o.SourceAsset) {
		return true
	}

	return false
}

// SetSourceAsset gets a reference to the given string and assigns it to the SourceAsset field.
func (o *Orchestration) SetSourceAsset(v string) {
	o.SourceAsset = &v
}

// GetDestinationAsset returns the DestinationAsset field value if set, zero value otherwise.
func (o *Orchestration) GetDestinationAsset() string {
	if o == nil || IsNil(o.DestinationAsset) {
		var ret string
		return ret
	}
	return *o.DestinationAsset
}

// GetDestinationAssetOk returns a tuple with the DestinationAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetDestinationAssetOk() (*string, bool) {
	if o == nil || IsNil(o.DestinationAsset) {
		return nil, false
	}
	return o.DestinationAsset, true
}

// HasDestinationAsset returns a boolean if a field has been set.
func (o *Orchestration) HasDestinationAsset() bool {
	if o != nil && !IsNil(o.DestinationAsset) {
		return true
	}

	return false
}

// SetDestinationAsset gets a reference to the given string and assigns it to the DestinationAsset field.
func (o *Orchestration) SetDestinationAsset(v string) {
	o.DestinationAsset = &v
}

// GetSourceAmount returns the SourceAmount field value if set, zero value otherwise.
func (o *Orchestration) GetSourceAmount() string {
	if o == nil || IsNil(o.SourceAmount) {
		var ret string
		return ret
	}
	return *o.SourceAmount
}

// GetSourceAmountOk returns a tuple with the SourceAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetSourceAmountOk() (*string, bool) {
	if o == nil || IsNil(o.SourceAmount) {
		return nil, false
	}
	return o.SourceAmount, true
}

// HasSourceAmount returns a boolean if a field has been set.
func (o *Orchestration) HasSourceAmount() bool {
	if o != nil && !IsNil(o.SourceAmount) {
		return true
	}

	return false
}

// SetSourceAmount gets a reference to the given string and assigns it to the SourceAmount field.
func (o *Orchestration) SetSourceAmount(v string) {
	o.SourceAmount = &v
}

// GetSourceTransfer returns the SourceTransfer field value if set, zero value otherwise.
func (o *Orchestration) GetSourceTransfer() TransferDetails {
	if o == nil || IsNil(o.SourceTransfer) {
		var ret TransferDetails
		return ret
	}
	return *o.SourceTransfer
}

// GetSourceTransferOk returns a tuple with the SourceTransfer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetSourceTransferOk() (*TransferDetails, bool) {
	if o == nil || IsNil(o.SourceTransfer) {
		return nil, false
	}
	return o.SourceTransfer, true
}

// HasSourceTransfer returns a boolean if a field has been set.
func (o *Orchestration) HasSourceTransfer() bool {
	if o != nil && !IsNil(o.SourceTransfer) {
		return true
	}

	return false
}

// SetSourceTransfer gets a reference to the given TransferDetails and assigns it to the SourceTransfer field.
func (o *Orchestration) SetSourceTransfer(v TransferDetails) {
	o.SourceTransfer = &v
}

// GetDestinationTransfer returns the DestinationTransfer field value if set, zero value otherwise.
func (o *Orchestration) GetDestinationTransfer() TransferDetails {
	if o == nil || IsNil(o.DestinationTransfer) {
		var ret TransferDetails
		return ret
	}
	return *o.DestinationTransfer
}

// GetDestinationTransferOk returns a tuple with the DestinationTransfer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetDestinationTransferOk() (*TransferDetails, bool) {
	if o == nil || IsNil(o.DestinationTransfer) {
		return nil, false
	}
	return o.DestinationTransfer, true
}

// HasDestinationTransfer returns a boolean if a field has been set.
func (o *Orchestration) HasDestinationTransfer() bool {
	if o != nil && !IsNil(o.DestinationTransfer) {
		return true
	}

	return false
}

// SetDestinationTransfer gets a reference to the given TransferDetails and assigns it to the DestinationTransfer field.
func (o *Orchestration) SetDestinationTransfer(v TransferDetails) {
	o.DestinationTransfer = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Orchestration) GetStatus() OrchestrationStatus {
	if o == nil || IsNil(o.Status) {
		var ret OrchestrationStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetStatusOk() (*OrchestrationStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Orchestration) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given OrchestrationStatus and assigns it to the Status field.
func (o *Orchestration) SetStatus(v OrchestrationStatus) {
	o.Status = &v
}

// GetFailReason returns the FailReason field value if set, zero value otherwise.
func (o *Orchestration) GetFailReason() FailReason {
	if o == nil || IsNil(o.FailReason) {
		var ret FailReason
		return ret
	}
	return *o.FailReason
}

// GetFailReasonOk returns a tuple with the FailReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetFailReasonOk() (*FailReason, bool) {
	if o == nil || IsNil(o.FailReason) {
		return nil, false
	}
	return o.FailReason, true
}

// HasFailReason returns a boolean if a field has been set.
func (o *Orchestration) HasFailReason() bool {
	if o != nil && !IsNil(o.FailReason) {
		return true
	}

	return false
}

// SetFailReason gets a reference to the given FailReason and assigns it to the FailReason field.
func (o *Orchestration) SetFailReason(v FailReason) {
	o.FailReason = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *Orchestration) GetSource() OrchestrationSource {
	if o == nil || IsNil(o.Source) {
		var ret OrchestrationSource
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetSourceOk() (*OrchestrationSource, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *Orchestration) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given OrchestrationSource and assigns it to the Source field.
func (o *Orchestration) SetSource(v OrchestrationSource) {
	o.Source = &v
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *Orchestration) GetDestination() OrchestrationDestination {
	if o == nil || IsNil(o.Destination) {
		var ret OrchestrationDestination
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetDestinationOk() (*OrchestrationDestination, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *Orchestration) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given OrchestrationDestination and assigns it to the Destination field.
func (o *Orchestration) SetDestination(v OrchestrationDestination) {
	o.Destination = &v
}

// GetOrchestrationRuleId returns the OrchestrationRuleId field value if set, zero value otherwise.
func (o *Orchestration) GetOrchestrationRuleId() string {
	if o == nil || IsNil(o.OrchestrationRuleId) {
		var ret string
		return ret
	}
	return *o.OrchestrationRuleId
}

// GetOrchestrationRuleIdOk returns a tuple with the OrchestrationRuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetOrchestrationRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrchestrationRuleId) {
		return nil, false
	}
	return o.OrchestrationRuleId, true
}

// HasOrchestrationRuleId returns a boolean if a field has been set.
func (o *Orchestration) HasOrchestrationRuleId() bool {
	if o != nil && !IsNil(o.OrchestrationRuleId) {
		return true
	}

	return false
}

// SetOrchestrationRuleId gets a reference to the given string and assigns it to the OrchestrationRuleId field.
func (o *Orchestration) SetOrchestrationRuleId(v string) {
	o.OrchestrationRuleId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Orchestration) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Orchestration) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Orchestration) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Orchestration) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Orchestration) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Orchestration) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Orchestration) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Orchestration) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Orchestration) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *Orchestration) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

func (o Orchestration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Orchestration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProfileId) {
		toSerialize["profile_id"] = o.ProfileId
	}
	if !IsNil(o.IdentityId) {
		toSerialize["identity_id"] = o.IdentityId
	}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	if !IsNil(o.RefId) {
		toSerialize["ref_id"] = o.RefId
	}
	if !IsNil(o.SourceAsset) {
		toSerialize["source_asset"] = o.SourceAsset
	}
	if !IsNil(o.DestinationAsset) {
		toSerialize["destination_asset"] = o.DestinationAsset
	}
	if !IsNil(o.SourceAmount) {
		toSerialize["source_amount"] = o.SourceAmount
	}
	if !IsNil(o.SourceTransfer) {
		toSerialize["source_transfer"] = o.SourceTransfer
	}
	if !IsNil(o.DestinationTransfer) {
		toSerialize["destination_transfer"] = o.DestinationTransfer
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.FailReason) {
		toSerialize["fail_reason"] = o.FailReason
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}
	if !IsNil(o.OrchestrationRuleId) {
		toSerialize["orchestration_rule_id"] = o.OrchestrationRuleId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Orchestration) UnmarshalJSON(data []byte) (err error) {
	varOrchestration := _Orchestration{}

	err = json.Unmarshal(data, &varOrchestration)

	if err != nil {
		return err
	}

	*o = Orchestration(varOrchestration)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "profile_id")
		delete(additionalProperties, "identity_id")
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "customer_id")
		delete(additionalProperties, "ref_id")
		delete(additionalProperties, "source_asset")
		delete(additionalProperties, "destination_asset")
		delete(additionalProperties, "source_amount")
		delete(additionalProperties, "source_transfer")
		delete(additionalProperties, "destination_transfer")
		delete(additionalProperties, "status")
		delete(additionalProperties, "fail_reason")
		delete(additionalProperties, "source")
		delete(additionalProperties, "destination")
		delete(additionalProperties, "orchestration_rule_id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrchestration struct {
	value *Orchestration
	isSet bool
}

func (v NullableOrchestration) Get() *Orchestration {
	return v.value
}

func (v *NullableOrchestration) Set(val *Orchestration) {
	v.value = val
	v.isSet = true
}

func (v NullableOrchestration) IsSet() bool {
	return v.isSet
}

func (v *NullableOrchestration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrchestration(val *Orchestration) *NullableOrchestration {
	return &NullableOrchestration{value: val, isSet: true}
}

func (v NullableOrchestration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrchestration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


