/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the ListTaxLotsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTaxLotsResponse{}

// ListTaxLotsResponse struct for ListTaxLotsResponse
type ListTaxLotsResponse struct {
	// Cursor token required for fetching the next page.
	NextPageCursor *string `json:"next_page_cursor,omitempty"`
	// The result list of tax lots.
	Items []TaxLot `json:"items,omitempty"`
}

// NewListTaxLotsResponse instantiates a new ListTaxLotsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTaxLotsResponse() *ListTaxLotsResponse {
	this := ListTaxLotsResponse{}
	return &this
}

// NewListTaxLotsResponseWithDefaults instantiates a new ListTaxLotsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTaxLotsResponseWithDefaults() *ListTaxLotsResponse {
	this := ListTaxLotsResponse{}
	return &this
}

// GetNextPageCursor returns the NextPageCursor field value if set, zero value otherwise.
func (o *ListTaxLotsResponse) GetNextPageCursor() string {
	if o == nil || IsNil(o.NextPageCursor) {
		var ret string
		return ret
	}
	return *o.NextPageCursor
}

// GetNextPageCursorOk returns a tuple with the NextPageCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTaxLotsResponse) GetNextPageCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageCursor) {
		return nil, false
	}
	return o.NextPageCursor, true
}

// HasNextPageCursor returns a boolean if a field has been set.
func (o *ListTaxLotsResponse) HasNextPageCursor() bool {
	if o != nil && !IsNil(o.NextPageCursor) {
		return true
	}

	return false
}

// SetNextPageCursor gets a reference to the given string and assigns it to the NextPageCursor field.
func (o *ListTaxLotsResponse) SetNextPageCursor(v string) {
	o.NextPageCursor = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ListTaxLotsResponse) GetItems() []TaxLot {
	if o == nil || IsNil(o.Items) {
		var ret []TaxLot
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListTaxLotsResponse) GetItemsOk() ([]TaxLot, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ListTaxLotsResponse) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []TaxLot and assigns it to the Items field.
func (o *ListTaxLotsResponse) SetItems(v []TaxLot) {
	o.Items = v
}

func (o ListTaxLotsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTaxLotsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextPageCursor) {
		toSerialize["next_page_cursor"] = o.NextPageCursor
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableListTaxLotsResponse struct {
	value *ListTaxLotsResponse
	isSet bool
}

func (v NullableListTaxLotsResponse) Get() *ListTaxLotsResponse {
	return v.value
}

func (v *NullableListTaxLotsResponse) Set(val *ListTaxLotsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListTaxLotsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListTaxLotsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTaxLotsResponse(val *ListTaxLotsResponse) *NullableListTaxLotsResponse {
	return &NullableListTaxLotsResponse{value: val, isSet: true}
}

func (v NullableListTaxLotsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTaxLotsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


