/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the CreateIdentityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIdentityRequest{}

// CreateIdentityRequest struct for CreateIdentityRequest
type CreateIdentityRequest struct {
	PersonDetails *PersonDetails `json:"person_details,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	// A user-facing ID to prevent duplicate identity creation. Unique for all identities created by the same API user.
	RefId *string `json:"ref_id,omitempty"`
	InstitutionDetails *InstitutionDetails `json:"institution_details,omitempty"`
	InstitutionMembers []InstitutionMember `json:"institution_members,omitempty"`
	// List of tax details associated with the identity. Must be set if tax_details_not_required is false or not set.
	TaxDetails []TaxDetail `json:"tax_details,omitempty"`
	// Set to true if tax details are not legally required.
	TaxDetailsNotRequired *bool `json:"tax_details_not_required,omitempty"`
	CustomerDueDiligence *CustomerDueDiligence `json:"customer_due_diligence,omitempty"`
	// Set to true if the identity is a merchant.
	IsMerchant *bool `json:"is_merchant,omitempty"`
}

// NewCreateIdentityRequest instantiates a new CreateIdentityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIdentityRequest() *CreateIdentityRequest {
	this := CreateIdentityRequest{}
	return &this
}

// NewCreateIdentityRequestWithDefaults instantiates a new CreateIdentityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIdentityRequestWithDefaults() *CreateIdentityRequest {
	this := CreateIdentityRequest{}
	return &this
}

// GetPersonDetails returns the PersonDetails field value if set, zero value otherwise.
func (o *CreateIdentityRequest) GetPersonDetails() PersonDetails {
	if o == nil || IsNil(o.PersonDetails) {
		var ret PersonDetails
		return ret
	}
	return *o.PersonDetails
}

// GetPersonDetailsOk returns a tuple with the PersonDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentityRequest) GetPersonDetailsOk() (*PersonDetails, bool) {
	if o == nil || IsNil(o.PersonDetails) {
		return nil, false
	}
	return o.PersonDetails, true
}

// HasPersonDetails returns a boolean if a field has been set.
func (o *CreateIdentityRequest) HasPersonDetails() bool {
	if o != nil && !IsNil(o.PersonDetails) {
		return true
	}

	return false
}

// SetPersonDetails gets a reference to the given PersonDetails and assigns it to the PersonDetails field.
func (o *CreateIdentityRequest) SetPersonDetails(v PersonDetails) {
	o.PersonDetails = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateIdentityRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentityRequest) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateIdentityRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *CreateIdentityRequest) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetRefId returns the RefId field value if set, zero value otherwise.
func (o *CreateIdentityRequest) GetRefId() string {
	if o == nil || IsNil(o.RefId) {
		var ret string
		return ret
	}
	return *o.RefId
}

// GetRefIdOk returns a tuple with the RefId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentityRequest) GetRefIdOk() (*string, bool) {
	if o == nil || IsNil(o.RefId) {
		return nil, false
	}
	return o.RefId, true
}

// HasRefId returns a boolean if a field has been set.
func (o *CreateIdentityRequest) HasRefId() bool {
	if o != nil && !IsNil(o.RefId) {
		return true
	}

	return false
}

// SetRefId gets a reference to the given string and assigns it to the RefId field.
func (o *CreateIdentityRequest) SetRefId(v string) {
	o.RefId = &v
}

// GetInstitutionDetails returns the InstitutionDetails field value if set, zero value otherwise.
func (o *CreateIdentityRequest) GetInstitutionDetails() InstitutionDetails {
	if o == nil || IsNil(o.InstitutionDetails) {
		var ret InstitutionDetails
		return ret
	}
	return *o.InstitutionDetails
}

// GetInstitutionDetailsOk returns a tuple with the InstitutionDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentityRequest) GetInstitutionDetailsOk() (*InstitutionDetails, bool) {
	if o == nil || IsNil(o.InstitutionDetails) {
		return nil, false
	}
	return o.InstitutionDetails, true
}

// HasInstitutionDetails returns a boolean if a field has been set.
func (o *CreateIdentityRequest) HasInstitutionDetails() bool {
	if o != nil && !IsNil(o.InstitutionDetails) {
		return true
	}

	return false
}

// SetInstitutionDetails gets a reference to the given InstitutionDetails and assigns it to the InstitutionDetails field.
func (o *CreateIdentityRequest) SetInstitutionDetails(v InstitutionDetails) {
	o.InstitutionDetails = &v
}

// GetInstitutionMembers returns the InstitutionMembers field value if set, zero value otherwise.
func (o *CreateIdentityRequest) GetInstitutionMembers() []InstitutionMember {
	if o == nil || IsNil(o.InstitutionMembers) {
		var ret []InstitutionMember
		return ret
	}
	return o.InstitutionMembers
}

// GetInstitutionMembersOk returns a tuple with the InstitutionMembers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentityRequest) GetInstitutionMembersOk() ([]InstitutionMember, bool) {
	if o == nil || IsNil(o.InstitutionMembers) {
		return nil, false
	}
	return o.InstitutionMembers, true
}

// HasInstitutionMembers returns a boolean if a field has been set.
func (o *CreateIdentityRequest) HasInstitutionMembers() bool {
	if o != nil && !IsNil(o.InstitutionMembers) {
		return true
	}

	return false
}

// SetInstitutionMembers gets a reference to the given []InstitutionMember and assigns it to the InstitutionMembers field.
func (o *CreateIdentityRequest) SetInstitutionMembers(v []InstitutionMember) {
	o.InstitutionMembers = v
}

// GetTaxDetails returns the TaxDetails field value if set, zero value otherwise.
func (o *CreateIdentityRequest) GetTaxDetails() []TaxDetail {
	if o == nil || IsNil(o.TaxDetails) {
		var ret []TaxDetail
		return ret
	}
	return o.TaxDetails
}

// GetTaxDetailsOk returns a tuple with the TaxDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentityRequest) GetTaxDetailsOk() ([]TaxDetail, bool) {
	if o == nil || IsNil(o.TaxDetails) {
		return nil, false
	}
	return o.TaxDetails, true
}

// HasTaxDetails returns a boolean if a field has been set.
func (o *CreateIdentityRequest) HasTaxDetails() bool {
	if o != nil && !IsNil(o.TaxDetails) {
		return true
	}

	return false
}

// SetTaxDetails gets a reference to the given []TaxDetail and assigns it to the TaxDetails field.
func (o *CreateIdentityRequest) SetTaxDetails(v []TaxDetail) {
	o.TaxDetails = v
}

// GetTaxDetailsNotRequired returns the TaxDetailsNotRequired field value if set, zero value otherwise.
func (o *CreateIdentityRequest) GetTaxDetailsNotRequired() bool {
	if o == nil || IsNil(o.TaxDetailsNotRequired) {
		var ret bool
		return ret
	}
	return *o.TaxDetailsNotRequired
}

// GetTaxDetailsNotRequiredOk returns a tuple with the TaxDetailsNotRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentityRequest) GetTaxDetailsNotRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.TaxDetailsNotRequired) {
		return nil, false
	}
	return o.TaxDetailsNotRequired, true
}

// HasTaxDetailsNotRequired returns a boolean if a field has been set.
func (o *CreateIdentityRequest) HasTaxDetailsNotRequired() bool {
	if o != nil && !IsNil(o.TaxDetailsNotRequired) {
		return true
	}

	return false
}

// SetTaxDetailsNotRequired gets a reference to the given bool and assigns it to the TaxDetailsNotRequired field.
func (o *CreateIdentityRequest) SetTaxDetailsNotRequired(v bool) {
	o.TaxDetailsNotRequired = &v
}

// GetCustomerDueDiligence returns the CustomerDueDiligence field value if set, zero value otherwise.
func (o *CreateIdentityRequest) GetCustomerDueDiligence() CustomerDueDiligence {
	if o == nil || IsNil(o.CustomerDueDiligence) {
		var ret CustomerDueDiligence
		return ret
	}
	return *o.CustomerDueDiligence
}

// GetCustomerDueDiligenceOk returns a tuple with the CustomerDueDiligence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentityRequest) GetCustomerDueDiligenceOk() (*CustomerDueDiligence, bool) {
	if o == nil || IsNil(o.CustomerDueDiligence) {
		return nil, false
	}
	return o.CustomerDueDiligence, true
}

// HasCustomerDueDiligence returns a boolean if a field has been set.
func (o *CreateIdentityRequest) HasCustomerDueDiligence() bool {
	if o != nil && !IsNil(o.CustomerDueDiligence) {
		return true
	}

	return false
}

// SetCustomerDueDiligence gets a reference to the given CustomerDueDiligence and assigns it to the CustomerDueDiligence field.
func (o *CreateIdentityRequest) SetCustomerDueDiligence(v CustomerDueDiligence) {
	o.CustomerDueDiligence = &v
}

// GetIsMerchant returns the IsMerchant field value if set, zero value otherwise.
func (o *CreateIdentityRequest) GetIsMerchant() bool {
	if o == nil || IsNil(o.IsMerchant) {
		var ret bool
		return ret
	}
	return *o.IsMerchant
}

// GetIsMerchantOk returns a tuple with the IsMerchant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIdentityRequest) GetIsMerchantOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMerchant) {
		return nil, false
	}
	return o.IsMerchant, true
}

// HasIsMerchant returns a boolean if a field has been set.
func (o *CreateIdentityRequest) HasIsMerchant() bool {
	if o != nil && !IsNil(o.IsMerchant) {
		return true
	}

	return false
}

// SetIsMerchant gets a reference to the given bool and assigns it to the IsMerchant field.
func (o *CreateIdentityRequest) SetIsMerchant(v bool) {
	o.IsMerchant = &v
}

func (o CreateIdentityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateIdentityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PersonDetails) {
		toSerialize["person_details"] = o.PersonDetails
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.RefId) {
		toSerialize["ref_id"] = o.RefId
	}
	if !IsNil(o.InstitutionDetails) {
		toSerialize["institution_details"] = o.InstitutionDetails
	}
	if !IsNil(o.InstitutionMembers) {
		toSerialize["institution_members"] = o.InstitutionMembers
	}
	if !IsNil(o.TaxDetails) {
		toSerialize["tax_details"] = o.TaxDetails
	}
	if !IsNil(o.TaxDetailsNotRequired) {
		toSerialize["tax_details_not_required"] = o.TaxDetailsNotRequired
	}
	if !IsNil(o.CustomerDueDiligence) {
		toSerialize["customer_due_diligence"] = o.CustomerDueDiligence
	}
	if !IsNil(o.IsMerchant) {
		toSerialize["is_merchant"] = o.IsMerchant
	}
	return toSerialize, nil
}

type NullableCreateIdentityRequest struct {
	value *CreateIdentityRequest
	isSet bool
}

func (v NullableCreateIdentityRequest) Get() *CreateIdentityRequest {
	return v.value
}

func (v *NullableCreateIdentityRequest) Set(val *CreateIdentityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIdentityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIdentityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIdentityRequest(val *CreateIdentityRequest) *NullableCreateIdentityRequest {
	return &NullableCreateIdentityRequest{value: val, isSet: true}
}

func (v NullableCreateIdentityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIdentityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


