/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the TransferDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferDetails{}

// TransferDetails TransferDetails refers to a specific Transfer and encodes its current status.
type TransferDetails struct {
	TransferId *string `json:"transfer_id,omitempty"`
	Status *TransferDetailsTransferStatus `json:"status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TransferDetails TransferDetails

// NewTransferDetails instantiates a new TransferDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferDetails() *TransferDetails {
	this := TransferDetails{}
	return &this
}

// NewTransferDetailsWithDefaults instantiates a new TransferDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferDetailsWithDefaults() *TransferDetails {
	this := TransferDetails{}
	return &this
}

// GetTransferId returns the TransferId field value if set, zero value otherwise.
func (o *TransferDetails) GetTransferId() string {
	if o == nil || IsNil(o.TransferId) {
		var ret string
		return ret
	}
	return *o.TransferId
}

// GetTransferIdOk returns a tuple with the TransferId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferDetails) GetTransferIdOk() (*string, bool) {
	if o == nil || IsNil(o.TransferId) {
		return nil, false
	}
	return o.TransferId, true
}

// HasTransferId returns a boolean if a field has been set.
func (o *TransferDetails) HasTransferId() bool {
	if o != nil && !IsNil(o.TransferId) {
		return true
	}

	return false
}

// SetTransferId gets a reference to the given string and assigns it to the TransferId field.
func (o *TransferDetails) SetTransferId(v string) {
	o.TransferId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TransferDetails) GetStatus() TransferDetailsTransferStatus {
	if o == nil || IsNil(o.Status) {
		var ret TransferDetailsTransferStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferDetails) GetStatusOk() (*TransferDetailsTransferStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TransferDetails) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given TransferDetailsTransferStatus and assigns it to the Status field.
func (o *TransferDetails) SetStatus(v TransferDetailsTransferStatus) {
	o.Status = &v
}

func (o TransferDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransferDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TransferId) {
		toSerialize["transfer_id"] = o.TransferId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TransferDetails) UnmarshalJSON(data []byte) (err error) {
	varTransferDetails := _TransferDetails{}

	err = json.Unmarshal(data, &varTransferDetails)

	if err != nil {
		return err
	}

	*o = TransferDetails(varTransferDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "transfer_id")
		delete(additionalProperties, "status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTransferDetails struct {
	value *TransferDetails
	isSet bool
}

func (v NullableTransferDetails) Get() *TransferDetails {
	return v.value
}

func (v *NullableTransferDetails) Set(val *TransferDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferDetails(val *TransferDetails) *NullableTransferDetails {
	return &NullableTransferDetails{value: val, isSet: true}
}

func (v NullableTransferDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


