/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateOrchestrationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrchestrationRequest{}

// CreateOrchestrationRequest struct for CreateOrchestrationRequest
type CreateOrchestrationRequest struct {
	IdentityId *string `json:"identity_id,omitempty"`
	AccountId *string `json:"account_id,omitempty"`
	// A client or system-specified unique identifier for the orchestration - used for idempotency protection. Retries of a request should use the same ref_id to avoid duplicate transactions.
	RefId string `json:"ref_id"`
	SourceAsset string `json:"source_asset"`
	DestinationAsset string `json:"destination_asset"`
	SourceAmount string `json:"source_amount"`
	Source *CreateOrchestrationRequestSource `json:"source,omitempty"`
	Destination *CreateOrchestrationRequestDestination `json:"destination,omitempty"`
	Metadata *map[string]string `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateOrchestrationRequest CreateOrchestrationRequest

// NewCreateOrchestrationRequest instantiates a new CreateOrchestrationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrchestrationRequest(refId string, sourceAsset string, destinationAsset string, sourceAmount string) *CreateOrchestrationRequest {
	this := CreateOrchestrationRequest{}
	this.RefId = refId
	this.SourceAsset = sourceAsset
	this.DestinationAsset = destinationAsset
	this.SourceAmount = sourceAmount
	return &this
}

// NewCreateOrchestrationRequestWithDefaults instantiates a new CreateOrchestrationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrchestrationRequestWithDefaults() *CreateOrchestrationRequest {
	this := CreateOrchestrationRequest{}
	return &this
}

// GetIdentityId returns the IdentityId field value if set, zero value otherwise.
func (o *CreateOrchestrationRequest) GetIdentityId() string {
	if o == nil || IsNil(o.IdentityId) {
		var ret string
		return ret
	}
	return *o.IdentityId
}

// GetIdentityIdOk returns a tuple with the IdentityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrchestrationRequest) GetIdentityIdOk() (*string, bool) {
	if o == nil || IsNil(o.IdentityId) {
		return nil, false
	}
	return o.IdentityId, true
}

// HasIdentityId returns a boolean if a field has been set.
func (o *CreateOrchestrationRequest) HasIdentityId() bool {
	if o != nil && !IsNil(o.IdentityId) {
		return true
	}

	return false
}

// SetIdentityId gets a reference to the given string and assigns it to the IdentityId field.
func (o *CreateOrchestrationRequest) SetIdentityId(v string) {
	o.IdentityId = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *CreateOrchestrationRequest) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrchestrationRequest) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *CreateOrchestrationRequest) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *CreateOrchestrationRequest) SetAccountId(v string) {
	o.AccountId = &v
}

// GetRefId returns the RefId field value
func (o *CreateOrchestrationRequest) GetRefId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefId
}

// GetRefIdOk returns a tuple with the RefId field value
// and a boolean to check if the value has been set.
func (o *CreateOrchestrationRequest) GetRefIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefId, true
}

// SetRefId sets field value
func (o *CreateOrchestrationRequest) SetRefId(v string) {
	o.RefId = v
}

// GetSourceAsset returns the SourceAsset field value
func (o *CreateOrchestrationRequest) GetSourceAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceAsset
}

// GetSourceAssetOk returns a tuple with the SourceAsset field value
// and a boolean to check if the value has been set.
func (o *CreateOrchestrationRequest) GetSourceAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceAsset, true
}

// SetSourceAsset sets field value
func (o *CreateOrchestrationRequest) SetSourceAsset(v string) {
	o.SourceAsset = v
}

// GetDestinationAsset returns the DestinationAsset field value
func (o *CreateOrchestrationRequest) GetDestinationAsset() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationAsset
}

// GetDestinationAssetOk returns a tuple with the DestinationAsset field value
// and a boolean to check if the value has been set.
func (o *CreateOrchestrationRequest) GetDestinationAssetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationAsset, true
}

// SetDestinationAsset sets field value
func (o *CreateOrchestrationRequest) SetDestinationAsset(v string) {
	o.DestinationAsset = v
}

// GetSourceAmount returns the SourceAmount field value
func (o *CreateOrchestrationRequest) GetSourceAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceAmount
}

// GetSourceAmountOk returns a tuple with the SourceAmount field value
// and a boolean to check if the value has been set.
func (o *CreateOrchestrationRequest) GetSourceAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceAmount, true
}

// SetSourceAmount sets field value
func (o *CreateOrchestrationRequest) SetSourceAmount(v string) {
	o.SourceAmount = v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *CreateOrchestrationRequest) GetSource() CreateOrchestrationRequestSource {
	if o == nil || IsNil(o.Source) {
		var ret CreateOrchestrationRequestSource
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrchestrationRequest) GetSourceOk() (*CreateOrchestrationRequestSource, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *CreateOrchestrationRequest) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given CreateOrchestrationRequestSource and assigns it to the Source field.
func (o *CreateOrchestrationRequest) SetSource(v CreateOrchestrationRequestSource) {
	o.Source = &v
}

// GetDestination returns the Destination field value if set, zero value otherwise.
func (o *CreateOrchestrationRequest) GetDestination() CreateOrchestrationRequestDestination {
	if o == nil || IsNil(o.Destination) {
		var ret CreateOrchestrationRequestDestination
		return ret
	}
	return *o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrchestrationRequest) GetDestinationOk() (*CreateOrchestrationRequestDestination, bool) {
	if o == nil || IsNil(o.Destination) {
		return nil, false
	}
	return o.Destination, true
}

// HasDestination returns a boolean if a field has been set.
func (o *CreateOrchestrationRequest) HasDestination() bool {
	if o != nil && !IsNil(o.Destination) {
		return true
	}

	return false
}

// SetDestination gets a reference to the given CreateOrchestrationRequestDestination and assigns it to the Destination field.
func (o *CreateOrchestrationRequest) SetDestination(v CreateOrchestrationRequestDestination) {
	o.Destination = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateOrchestrationRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrchestrationRequest) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateOrchestrationRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *CreateOrchestrationRequest) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

func (o CreateOrchestrationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrchestrationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IdentityId) {
		toSerialize["identity_id"] = o.IdentityId
	}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	toSerialize["ref_id"] = o.RefId
	toSerialize["source_asset"] = o.SourceAsset
	toSerialize["destination_asset"] = o.DestinationAsset
	toSerialize["source_amount"] = o.SourceAmount
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	if !IsNil(o.Destination) {
		toSerialize["destination"] = o.Destination
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOrchestrationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ref_id",
		"source_asset",
		"destination_asset",
		"source_amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrchestrationRequest := _CreateOrchestrationRequest{}

	err = json.Unmarshal(data, &varCreateOrchestrationRequest)

	if err != nil {
		return err
	}

	*o = CreateOrchestrationRequest(varCreateOrchestrationRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "identity_id")
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "ref_id")
		delete(additionalProperties, "source_asset")
		delete(additionalProperties, "destination_asset")
		delete(additionalProperties, "source_amount")
		delete(additionalProperties, "source")
		delete(additionalProperties, "destination")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOrchestrationRequest struct {
	value *CreateOrchestrationRequest
	isSet bool
}

func (v NullableCreateOrchestrationRequest) Get() *CreateOrchestrationRequest {
	return v.value
}

func (v *NullableCreateOrchestrationRequest) Set(val *CreateOrchestrationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrchestrationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrchestrationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrchestrationRequest(val *CreateOrchestrationRequest) *NullableCreateOrchestrationRequest {
	return &NullableCreateOrchestrationRequest{value: val, isSet: true}
}

func (v NullableCreateOrchestrationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrchestrationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


