/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
	"fmt"
)

// ListIssuerQuoteExecutionsRequestStatus the model 'ListIssuerQuoteExecutionsRequestStatus'
type ListIssuerQuoteExecutionsRequestStatus string

// List of ListIssuerQuoteExecutionsRequestStatus
const (
	ListIssuerQuoteExecutionsRequestStatus_PENDING ListIssuerQuoteExecutionsRequestStatus = "PENDING"
	ListIssuerQuoteExecutionsRequestStatus_COMPLETE ListIssuerQuoteExecutionsRequestStatus = "COMPLETE"
	ListIssuerQuoteExecutionsRequestStatus_FAILED ListIssuerQuoteExecutionsRequestStatus = "FAILED"
)

// All allowed values of ListIssuerQuoteExecutionsRequestStatus enum
var AllowedListIssuerQuoteExecutionsRequestStatusEnumValues = []ListIssuerQuoteExecutionsRequestStatus{
	"PENDING",
	"COMPLETE",
	"FAILED",
}

func (v *ListIssuerQuoteExecutionsRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ListIssuerQuoteExecutionsRequestStatus(value)
	for _, existing := range AllowedListIssuerQuoteExecutionsRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ListIssuerQuoteExecutionsRequestStatus", value)
}

// NewListIssuerQuoteExecutionsRequestStatusFromValue returns a pointer to a valid ListIssuerQuoteExecutionsRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewListIssuerQuoteExecutionsRequestStatusFromValue(v string) (*ListIssuerQuoteExecutionsRequestStatus, error) {
	ev := ListIssuerQuoteExecutionsRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ListIssuerQuoteExecutionsRequestStatus: valid values are %v", v, AllowedListIssuerQuoteExecutionsRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ListIssuerQuoteExecutionsRequestStatus) IsValid() bool {
	for _, existing := range AllowedListIssuerQuoteExecutionsRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ListIssuerQuoteExecutionsRequestStatus value
func (v ListIssuerQuoteExecutionsRequestStatus) Ptr() *ListIssuerQuoteExecutionsRequestStatus {
	return &v
}

type NullableListIssuerQuoteExecutionsRequestStatus struct {
	value *ListIssuerQuoteExecutionsRequestStatus
	isSet bool
}

func (v NullableListIssuerQuoteExecutionsRequestStatus) Get() *ListIssuerQuoteExecutionsRequestStatus {
	return v.value
}

func (v *NullableListIssuerQuoteExecutionsRequestStatus) Set(val *ListIssuerQuoteExecutionsRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableListIssuerQuoteExecutionsRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableListIssuerQuoteExecutionsRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIssuerQuoteExecutionsRequestStatus(val *ListIssuerQuoteExecutionsRequestStatus) *NullableListIssuerQuoteExecutionsRequestStatus {
	return &NullableListIssuerQuoteExecutionsRequestStatus{value: val, isSet: true}
}

func (v NullableListIssuerQuoteExecutionsRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIssuerQuoteExecutionsRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

