/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the MonitoringAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonitoringAddress{}

// MonitoringAddress struct for MonitoringAddress
type MonitoringAddress struct {
	// On-chain address Paxos will monitor for eligible reward activity.
	Address string `json:"address"`
	CryptoNetwork CryptoNetwork `json:"crypto_network"`
	// Optional display name. Useful for grouping or reporting.
	Name *string `json:"name,omitempty"`
	// When the address was registered.
	CreatedAt time.Time `json:"created_at"`
	// UUID direct reference to the created address (to be used for updates).
	Id string `json:"id"`
	AdditionalProperties map[string]interface{}
}

type _MonitoringAddress MonitoringAddress

// NewMonitoringAddress instantiates a new MonitoringAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonitoringAddress(address string, cryptoNetwork CryptoNetwork, createdAt time.Time, id string) *MonitoringAddress {
	this := MonitoringAddress{}
	this.Address = address
	this.CryptoNetwork = cryptoNetwork
	this.CreatedAt = createdAt
	this.Id = id
	return &this
}

// NewMonitoringAddressWithDefaults instantiates a new MonitoringAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonitoringAddressWithDefaults() *MonitoringAddress {
	this := MonitoringAddress{}
	return &this
}

// GetAddress returns the Address field value
func (o *MonitoringAddress) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *MonitoringAddress) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *MonitoringAddress) SetAddress(v string) {
	o.Address = v
}

// GetCryptoNetwork returns the CryptoNetwork field value
func (o *MonitoringAddress) GetCryptoNetwork() CryptoNetwork {
	if o == nil {
		var ret CryptoNetwork
		return ret
	}

	return o.CryptoNetwork
}

// GetCryptoNetworkOk returns a tuple with the CryptoNetwork field value
// and a boolean to check if the value has been set.
func (o *MonitoringAddress) GetCryptoNetworkOk() (*CryptoNetwork, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CryptoNetwork, true
}

// SetCryptoNetwork sets field value
func (o *MonitoringAddress) SetCryptoNetwork(v CryptoNetwork) {
	o.CryptoNetwork = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MonitoringAddress) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitoringAddress) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MonitoringAddress) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MonitoringAddress) SetName(v string) {
	o.Name = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *MonitoringAddress) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *MonitoringAddress) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *MonitoringAddress) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *MonitoringAddress) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MonitoringAddress) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MonitoringAddress) SetId(v string) {
	o.Id = v
}

func (o MonitoringAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonitoringAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["crypto_network"] = o.CryptoNetwork
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["id"] = o.Id

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MonitoringAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"crypto_network",
		"created_at",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMonitoringAddress := _MonitoringAddress{}

	err = json.Unmarshal(data, &varMonitoringAddress)

	if err != nil {
		return err
	}

	*o = MonitoringAddress(varMonitoringAddress)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "crypto_network")
		delete(additionalProperties, "name")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMonitoringAddress struct {
	value *MonitoringAddress
	isSet bool
}

func (v NullableMonitoringAddress) Get() *MonitoringAddress {
	return v.value
}

func (v *NullableMonitoringAddress) Set(val *MonitoringAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableMonitoringAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableMonitoringAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonitoringAddress(val *MonitoringAddress) *NullableMonitoringAddress {
	return &NullableMonitoringAddress{value: val, isSet: true}
}

func (v NullableMonitoringAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonitoringAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


