/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the CreateMonitoringAddressResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMonitoringAddressResponse{}

// CreateMonitoringAddressResponse struct for CreateMonitoringAddressResponse
type CreateMonitoringAddressResponse struct {
	Address *MonitoringAddress `json:"address,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateMonitoringAddressResponse CreateMonitoringAddressResponse

// NewCreateMonitoringAddressResponse instantiates a new CreateMonitoringAddressResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMonitoringAddressResponse() *CreateMonitoringAddressResponse {
	this := CreateMonitoringAddressResponse{}
	return &this
}

// NewCreateMonitoringAddressResponseWithDefaults instantiates a new CreateMonitoringAddressResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMonitoringAddressResponseWithDefaults() *CreateMonitoringAddressResponse {
	this := CreateMonitoringAddressResponse{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *CreateMonitoringAddressResponse) GetAddress() MonitoringAddress {
	if o == nil || IsNil(o.Address) {
		var ret MonitoringAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMonitoringAddressResponse) GetAddressOk() (*MonitoringAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *CreateMonitoringAddressResponse) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given MonitoringAddress and assigns it to the Address field.
func (o *CreateMonitoringAddressResponse) SetAddress(v MonitoringAddress) {
	o.Address = &v
}

func (o CreateMonitoringAddressResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMonitoringAddressResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateMonitoringAddressResponse) UnmarshalJSON(data []byte) (err error) {
	varCreateMonitoringAddressResponse := _CreateMonitoringAddressResponse{}

	err = json.Unmarshal(data, &varCreateMonitoringAddressResponse)

	if err != nil {
		return err
	}

	*o = CreateMonitoringAddressResponse(varCreateMonitoringAddressResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateMonitoringAddressResponse struct {
	value *CreateMonitoringAddressResponse
	isSet bool
}

func (v NullableCreateMonitoringAddressResponse) Get() *CreateMonitoringAddressResponse {
	return v.value
}

func (v *NullableCreateMonitoringAddressResponse) Set(val *CreateMonitoringAddressResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMonitoringAddressResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMonitoringAddressResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMonitoringAddressResponse(val *CreateMonitoringAddressResponse) *NullableCreateMonitoringAddressResponse {
	return &NullableCreateMonitoringAddressResponse{value: val, isSet: true}
}

func (v NullableCreateMonitoringAddressResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMonitoringAddressResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


