/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the IssuerQuoteExecution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssuerQuoteExecution{}

// IssuerQuoteExecution struct for IssuerQuoteExecution
type IssuerQuoteExecution struct {
	// The UUID of the issuer quote execution.
	Id string `json:"id"`
	// The time at which the issuer quote execution was created.
	CreatedAt time.Time `json:"created_at"`
	// The crypto asset bought or sold with the issuer quote execution.
	AssetType string `json:"asset_type"`
	// The notional amount of the issuer quote execution.
	Principal string `json:"principal"`
	// The fee charged for the issuer quote execution.
	Fee string `json:"fee"`
	Status IssuerQuoteExecutionStatus `json:"status"`
	// A unique identifier for the quote execution (for idempotence).
	RefId *string `json:"ref_id,omitempty"`
	// The creation or destruction fee, denominated in crypto units.
	TokenFee string `json:"token_fee"`
	// The price of the crypto asset at the time of the transaction.
	TokenPrice string `json:"token_price"`
	// The net amount of the crypto asset received. Can be negative.
	TokenPrincipal string `json:"token_principal"`
	// The profile ID under which the issuer quote is executed.
	ProfileId string `json:"profile_id"`
	AdditionalProperties map[string]interface{}
}

type _IssuerQuoteExecution IssuerQuoteExecution

// NewIssuerQuoteExecution instantiates a new IssuerQuoteExecution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssuerQuoteExecution(id string, createdAt time.Time, assetType string, principal string, fee string, status IssuerQuoteExecutionStatus, tokenFee string, tokenPrice string, tokenPrincipal string, profileId string) *IssuerQuoteExecution {
	this := IssuerQuoteExecution{}
	this.Id = id
	this.CreatedAt = createdAt
	this.AssetType = assetType
	this.Principal = principal
	this.Fee = fee
	this.Status = status
	this.TokenFee = tokenFee
	this.TokenPrice = tokenPrice
	this.TokenPrincipal = tokenPrincipal
	this.ProfileId = profileId
	return &this
}

// NewIssuerQuoteExecutionWithDefaults instantiates a new IssuerQuoteExecution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssuerQuoteExecutionWithDefaults() *IssuerQuoteExecution {
	this := IssuerQuoteExecution{}
	return &this
}

// GetId returns the Id field value
func (o *IssuerQuoteExecution) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IssuerQuoteExecution) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *IssuerQuoteExecution) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *IssuerQuoteExecution) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetAssetType returns the AssetType field value
func (o *IssuerQuoteExecution) GetAssetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetType
}

// GetAssetTypeOk returns a tuple with the AssetType field value
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetAssetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetType, true
}

// SetAssetType sets field value
func (o *IssuerQuoteExecution) SetAssetType(v string) {
	o.AssetType = v
}

// GetPrincipal returns the Principal field value
func (o *IssuerQuoteExecution) GetPrincipal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetPrincipalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Principal, true
}

// SetPrincipal sets field value
func (o *IssuerQuoteExecution) SetPrincipal(v string) {
	o.Principal = v
}

// GetFee returns the Fee field value
func (o *IssuerQuoteExecution) GetFee() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Fee
}

// GetFeeOk returns a tuple with the Fee field value
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetFeeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fee, true
}

// SetFee sets field value
func (o *IssuerQuoteExecution) SetFee(v string) {
	o.Fee = v
}

// GetStatus returns the Status field value
func (o *IssuerQuoteExecution) GetStatus() IssuerQuoteExecutionStatus {
	if o == nil {
		var ret IssuerQuoteExecutionStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetStatusOk() (*IssuerQuoteExecutionStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *IssuerQuoteExecution) SetStatus(v IssuerQuoteExecutionStatus) {
	o.Status = v
}

// GetRefId returns the RefId field value if set, zero value otherwise.
func (o *IssuerQuoteExecution) GetRefId() string {
	if o == nil || IsNil(o.RefId) {
		var ret string
		return ret
	}
	return *o.RefId
}

// GetRefIdOk returns a tuple with the RefId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetRefIdOk() (*string, bool) {
	if o == nil || IsNil(o.RefId) {
		return nil, false
	}
	return o.RefId, true
}

// HasRefId returns a boolean if a field has been set.
func (o *IssuerQuoteExecution) HasRefId() bool {
	if o != nil && !IsNil(o.RefId) {
		return true
	}

	return false
}

// SetRefId gets a reference to the given string and assigns it to the RefId field.
func (o *IssuerQuoteExecution) SetRefId(v string) {
	o.RefId = &v
}

// GetTokenFee returns the TokenFee field value
func (o *IssuerQuoteExecution) GetTokenFee() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenFee
}

// GetTokenFeeOk returns a tuple with the TokenFee field value
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetTokenFeeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenFee, true
}

// SetTokenFee sets field value
func (o *IssuerQuoteExecution) SetTokenFee(v string) {
	o.TokenFee = v
}

// GetTokenPrice returns the TokenPrice field value
func (o *IssuerQuoteExecution) GetTokenPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenPrice
}

// GetTokenPriceOk returns a tuple with the TokenPrice field value
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetTokenPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenPrice, true
}

// SetTokenPrice sets field value
func (o *IssuerQuoteExecution) SetTokenPrice(v string) {
	o.TokenPrice = v
}

// GetTokenPrincipal returns the TokenPrincipal field value
func (o *IssuerQuoteExecution) GetTokenPrincipal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenPrincipal
}

// GetTokenPrincipalOk returns a tuple with the TokenPrincipal field value
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetTokenPrincipalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenPrincipal, true
}

// SetTokenPrincipal sets field value
func (o *IssuerQuoteExecution) SetTokenPrincipal(v string) {
	o.TokenPrincipal = v
}

// GetProfileId returns the ProfileId field value
func (o *IssuerQuoteExecution) GetProfileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value
// and a boolean to check if the value has been set.
func (o *IssuerQuoteExecution) GetProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProfileId, true
}

// SetProfileId sets field value
func (o *IssuerQuoteExecution) SetProfileId(v string) {
	o.ProfileId = v
}

func (o IssuerQuoteExecution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssuerQuoteExecution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["asset_type"] = o.AssetType
	toSerialize["principal"] = o.Principal
	toSerialize["fee"] = o.Fee
	toSerialize["status"] = o.Status
	if !IsNil(o.RefId) {
		toSerialize["ref_id"] = o.RefId
	}
	toSerialize["token_fee"] = o.TokenFee
	toSerialize["token_price"] = o.TokenPrice
	toSerialize["token_principal"] = o.TokenPrincipal
	toSerialize["profile_id"] = o.ProfileId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IssuerQuoteExecution) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created_at",
		"asset_type",
		"principal",
		"fee",
		"status",
		"token_fee",
		"token_price",
		"token_principal",
		"profile_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIssuerQuoteExecution := _IssuerQuoteExecution{}

	err = json.Unmarshal(data, &varIssuerQuoteExecution)

	if err != nil {
		return err
	}

	*o = IssuerQuoteExecution(varIssuerQuoteExecution)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "asset_type")
		delete(additionalProperties, "principal")
		delete(additionalProperties, "fee")
		delete(additionalProperties, "status")
		delete(additionalProperties, "ref_id")
		delete(additionalProperties, "token_fee")
		delete(additionalProperties, "token_price")
		delete(additionalProperties, "token_principal")
		delete(additionalProperties, "profile_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIssuerQuoteExecution struct {
	value *IssuerQuoteExecution
	isSet bool
}

func (v NullableIssuerQuoteExecution) Get() *IssuerQuoteExecution {
	return v.value
}

func (v *NullableIssuerQuoteExecution) Set(val *IssuerQuoteExecution) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuerQuoteExecution) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuerQuoteExecution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuerQuoteExecution(val *IssuerQuoteExecution) *NullableIssuerQuoteExecution {
	return &NullableIssuerQuoteExecution{value: val, isSet: true}
}

func (v NullableIssuerQuoteExecution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuerQuoteExecution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


