/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
	"fmt"
)

// CustodianType the model 'CustodianType'
type CustodianType string

// List of CustodianType
const (
	CustodianType_VASP CustodianType = "VASP"
	CustodianType_PRIVATE CustodianType = "PRIVATE"
)

// All allowed values of CustodianType enum
var AllowedCustodianTypeEnumValues = []CustodianType{
	"VASP",
	"PRIVATE",
}

func (v *CustodianType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CustodianType(value)
	for _, existing := range AllowedCustodianTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CustodianType", value)
}

// NewCustodianTypeFromValue returns a pointer to a valid CustodianType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCustodianTypeFromValue(v string) (*CustodianType, error) {
	ev := CustodianType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CustodianType: valid values are %v", v, AllowedCustodianTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CustodianType) IsValid() bool {
	for _, existing := range AllowedCustodianTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CustodianType value
func (v CustodianType) Ptr() *CustodianType {
	return &v
}

type NullableCustodianType struct {
	value *CustodianType
	isSet bool
}

func (v NullableCustodianType) Get() *CustodianType {
	return v.value
}

func (v *NullableCustodianType) Set(val *CustodianType) {
	v.value = val
	v.isSet = true
}

func (v NullableCustodianType) IsSet() bool {
	return v.isSet
}

func (v *NullableCustodianType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustodianType(val *CustodianType) *NullableCustodianType {
	return &NullableCustodianType{value: val, isSet: true}
}

func (v NullableCustodianType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustodianType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

