/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the AddAccountMembersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAccountMembersResponse{}

// AddAccountMembersResponse struct for AddAccountMembersResponse
type AddAccountMembersResponse struct {
	// ID of account to which members were added.
	AccountId *string `json:"account_id,omitempty"`
	// List of account members that were added to the account.
	Members []AccountMember `json:"members,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AddAccountMembersResponse AddAccountMembersResponse

// NewAddAccountMembersResponse instantiates a new AddAccountMembersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAccountMembersResponse() *AddAccountMembersResponse {
	this := AddAccountMembersResponse{}
	return &this
}

// NewAddAccountMembersResponseWithDefaults instantiates a new AddAccountMembersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAccountMembersResponseWithDefaults() *AddAccountMembersResponse {
	this := AddAccountMembersResponse{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *AddAccountMembersResponse) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAccountMembersResponse) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *AddAccountMembersResponse) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *AddAccountMembersResponse) SetAccountId(v string) {
	o.AccountId = &v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *AddAccountMembersResponse) GetMembers() []AccountMember {
	if o == nil || IsNil(o.Members) {
		var ret []AccountMember
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAccountMembersResponse) GetMembersOk() ([]AccountMember, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *AddAccountMembersResponse) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []AccountMember and assigns it to the Members field.
func (o *AddAccountMembersResponse) SetMembers(v []AccountMember) {
	o.Members = v
}

func (o AddAccountMembersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAccountMembersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddAccountMembersResponse) UnmarshalJSON(data []byte) (err error) {
	varAddAccountMembersResponse := _AddAccountMembersResponse{}

	err = json.Unmarshal(data, &varAddAccountMembersResponse)

	if err != nil {
		return err
	}

	*o = AddAccountMembersResponse(varAddAccountMembersResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "members")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddAccountMembersResponse struct {
	value *AddAccountMembersResponse
	isSet bool
}

func (v NullableAddAccountMembersResponse) Get() *AddAccountMembersResponse {
	return v.value
}

func (v *NullableAddAccountMembersResponse) Set(val *AddAccountMembersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAccountMembersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAccountMembersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAccountMembersResponse(val *AddAccountMembersResponse) *NullableAddAccountMembersResponse {
	return &NullableAddAccountMembersResponse{value: val, isSet: true}
}

func (v NullableAddAccountMembersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAccountMembersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


