/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the StatementBalance type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatementBalance{}

// StatementBalance struct for StatementBalance
type StatementBalance struct {
	Asset *string `json:"asset,omitempty"`
	AmountPaid *string `json:"amount_paid,omitempty"`
	TotalAmountOwed *string `json:"total_amount_owed,omitempty"`
	// next_payment_ref_id should be used by clients as the ref_id when processing payments for statements. This is unique to for each payment that should be submitted. If the amount_paid == total_amount_owed, then this field will be empty.
	NextPaymentRefId *string `json:"next_payment_ref_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StatementBalance StatementBalance

// NewStatementBalance instantiates a new StatementBalance object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatementBalance() *StatementBalance {
	this := StatementBalance{}
	return &this
}

// NewStatementBalanceWithDefaults instantiates a new StatementBalance object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatementBalanceWithDefaults() *StatementBalance {
	this := StatementBalance{}
	return &this
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *StatementBalance) GetAsset() string {
	if o == nil || IsNil(o.Asset) {
		var ret string
		return ret
	}
	return *o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementBalance) GetAssetOk() (*string, bool) {
	if o == nil || IsNil(o.Asset) {
		return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *StatementBalance) HasAsset() bool {
	if o != nil && !IsNil(o.Asset) {
		return true
	}

	return false
}

// SetAsset gets a reference to the given string and assigns it to the Asset field.
func (o *StatementBalance) SetAsset(v string) {
	o.Asset = &v
}

// GetAmountPaid returns the AmountPaid field value if set, zero value otherwise.
func (o *StatementBalance) GetAmountPaid() string {
	if o == nil || IsNil(o.AmountPaid) {
		var ret string
		return ret
	}
	return *o.AmountPaid
}

// GetAmountPaidOk returns a tuple with the AmountPaid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementBalance) GetAmountPaidOk() (*string, bool) {
	if o == nil || IsNil(o.AmountPaid) {
		return nil, false
	}
	return o.AmountPaid, true
}

// HasAmountPaid returns a boolean if a field has been set.
func (o *StatementBalance) HasAmountPaid() bool {
	if o != nil && !IsNil(o.AmountPaid) {
		return true
	}

	return false
}

// SetAmountPaid gets a reference to the given string and assigns it to the AmountPaid field.
func (o *StatementBalance) SetAmountPaid(v string) {
	o.AmountPaid = &v
}

// GetTotalAmountOwed returns the TotalAmountOwed field value if set, zero value otherwise.
func (o *StatementBalance) GetTotalAmountOwed() string {
	if o == nil || IsNil(o.TotalAmountOwed) {
		var ret string
		return ret
	}
	return *o.TotalAmountOwed
}

// GetTotalAmountOwedOk returns a tuple with the TotalAmountOwed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementBalance) GetTotalAmountOwedOk() (*string, bool) {
	if o == nil || IsNil(o.TotalAmountOwed) {
		return nil, false
	}
	return o.TotalAmountOwed, true
}

// HasTotalAmountOwed returns a boolean if a field has been set.
func (o *StatementBalance) HasTotalAmountOwed() bool {
	if o != nil && !IsNil(o.TotalAmountOwed) {
		return true
	}

	return false
}

// SetTotalAmountOwed gets a reference to the given string and assigns it to the TotalAmountOwed field.
func (o *StatementBalance) SetTotalAmountOwed(v string) {
	o.TotalAmountOwed = &v
}

// GetNextPaymentRefId returns the NextPaymentRefId field value if set, zero value otherwise.
func (o *StatementBalance) GetNextPaymentRefId() string {
	if o == nil || IsNil(o.NextPaymentRefId) {
		var ret string
		return ret
	}
	return *o.NextPaymentRefId
}

// GetNextPaymentRefIdOk returns a tuple with the NextPaymentRefId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementBalance) GetNextPaymentRefIdOk() (*string, bool) {
	if o == nil || IsNil(o.NextPaymentRefId) {
		return nil, false
	}
	return o.NextPaymentRefId, true
}

// HasNextPaymentRefId returns a boolean if a field has been set.
func (o *StatementBalance) HasNextPaymentRefId() bool {
	if o != nil && !IsNil(o.NextPaymentRefId) {
		return true
	}

	return false
}

// SetNextPaymentRefId gets a reference to the given string and assigns it to the NextPaymentRefId field.
func (o *StatementBalance) SetNextPaymentRefId(v string) {
	o.NextPaymentRefId = &v
}

func (o StatementBalance) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatementBalance) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Asset) {
		toSerialize["asset"] = o.Asset
	}
	if !IsNil(o.AmountPaid) {
		toSerialize["amount_paid"] = o.AmountPaid
	}
	if !IsNil(o.TotalAmountOwed) {
		toSerialize["total_amount_owed"] = o.TotalAmountOwed
	}
	if !IsNil(o.NextPaymentRefId) {
		toSerialize["next_payment_ref_id"] = o.NextPaymentRefId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StatementBalance) UnmarshalJSON(data []byte) (err error) {
	varStatementBalance := _StatementBalance{}

	err = json.Unmarshal(data, &varStatementBalance)

	if err != nil {
		return err
	}

	*o = StatementBalance(varStatementBalance)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "asset")
		delete(additionalProperties, "amount_paid")
		delete(additionalProperties, "total_amount_owed")
		delete(additionalProperties, "next_payment_ref_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStatementBalance struct {
	value *StatementBalance
	isSet bool
}

func (v NullableStatementBalance) Get() *StatementBalance {
	return v.value
}

func (v *NullableStatementBalance) Set(val *StatementBalance) {
	v.value = val
	v.isSet = true
}

func (v NullableStatementBalance) IsSet() bool {
	return v.isSet
}

func (v *NullableStatementBalance) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatementBalance(val *StatementBalance) *NullableStatementBalance {
	return &NullableStatementBalance{value: val, isSet: true}
}

func (v NullableStatementBalance) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatementBalance) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


