/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the ListCryptoDestinationAddressesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCryptoDestinationAddressesResponse{}

// ListCryptoDestinationAddressesResponse struct for ListCryptoDestinationAddressesResponse
type ListCryptoDestinationAddressesResponse struct {
	Addresses []CryptoDestinationAddress `json:"addresses,omitempty"`
	NextPageCursor *string `json:"next_page_cursor,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListCryptoDestinationAddressesResponse ListCryptoDestinationAddressesResponse

// NewListCryptoDestinationAddressesResponse instantiates a new ListCryptoDestinationAddressesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCryptoDestinationAddressesResponse() *ListCryptoDestinationAddressesResponse {
	this := ListCryptoDestinationAddressesResponse{}
	return &this
}

// NewListCryptoDestinationAddressesResponseWithDefaults instantiates a new ListCryptoDestinationAddressesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCryptoDestinationAddressesResponseWithDefaults() *ListCryptoDestinationAddressesResponse {
	this := ListCryptoDestinationAddressesResponse{}
	return &this
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *ListCryptoDestinationAddressesResponse) GetAddresses() []CryptoDestinationAddress {
	if o == nil || IsNil(o.Addresses) {
		var ret []CryptoDestinationAddress
		return ret
	}
	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCryptoDestinationAddressesResponse) GetAddressesOk() ([]CryptoDestinationAddress, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *ListCryptoDestinationAddressesResponse) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []CryptoDestinationAddress and assigns it to the Addresses field.
func (o *ListCryptoDestinationAddressesResponse) SetAddresses(v []CryptoDestinationAddress) {
	o.Addresses = v
}

// GetNextPageCursor returns the NextPageCursor field value if set, zero value otherwise.
func (o *ListCryptoDestinationAddressesResponse) GetNextPageCursor() string {
	if o == nil || IsNil(o.NextPageCursor) {
		var ret string
		return ret
	}
	return *o.NextPageCursor
}

// GetNextPageCursorOk returns a tuple with the NextPageCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCryptoDestinationAddressesResponse) GetNextPageCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageCursor) {
		return nil, false
	}
	return o.NextPageCursor, true
}

// HasNextPageCursor returns a boolean if a field has been set.
func (o *ListCryptoDestinationAddressesResponse) HasNextPageCursor() bool {
	if o != nil && !IsNil(o.NextPageCursor) {
		return true
	}

	return false
}

// SetNextPageCursor gets a reference to the given string and assigns it to the NextPageCursor field.
func (o *ListCryptoDestinationAddressesResponse) SetNextPageCursor(v string) {
	o.NextPageCursor = &v
}

func (o ListCryptoDestinationAddressesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCryptoDestinationAddressesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	if !IsNil(o.NextPageCursor) {
		toSerialize["next_page_cursor"] = o.NextPageCursor
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListCryptoDestinationAddressesResponse) UnmarshalJSON(data []byte) (err error) {
	varListCryptoDestinationAddressesResponse := _ListCryptoDestinationAddressesResponse{}

	err = json.Unmarshal(data, &varListCryptoDestinationAddressesResponse)

	if err != nil {
		return err
	}

	*o = ListCryptoDestinationAddressesResponse(varListCryptoDestinationAddressesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "addresses")
		delete(additionalProperties, "next_page_cursor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListCryptoDestinationAddressesResponse struct {
	value *ListCryptoDestinationAddressesResponse
	isSet bool
}

func (v NullableListCryptoDestinationAddressesResponse) Get() *ListCryptoDestinationAddressesResponse {
	return v.value
}

func (v *NullableListCryptoDestinationAddressesResponse) Set(val *ListCryptoDestinationAddressesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListCryptoDestinationAddressesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListCryptoDestinationAddressesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCryptoDestinationAddressesResponse(val *ListCryptoDestinationAddressesResponse) *NullableListCryptoDestinationAddressesResponse {
	return &NullableListCryptoDestinationAddressesResponse{value: val, isSet: true}
}

func (v NullableListCryptoDestinationAddressesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCryptoDestinationAddressesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


