/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
	"fmt"
)

// IssuerQuoteExecutionStatus the model 'IssuerQuoteExecutionStatus'
type IssuerQuoteExecutionStatus string

// List of IssuerQuoteExecutionStatus
const (
	IssuerQuoteExecutionStatus_PENDING IssuerQuoteExecutionStatus = "PENDING"
	IssuerQuoteExecutionStatus_COMPLETE IssuerQuoteExecutionStatus = "COMPLETE"
	IssuerQuoteExecutionStatus_FAILED IssuerQuoteExecutionStatus = "FAILED"
)

// All allowed values of IssuerQuoteExecutionStatus enum
var AllowedIssuerQuoteExecutionStatusEnumValues = []IssuerQuoteExecutionStatus{
	"PENDING",
	"COMPLETE",
	"FAILED",
}

func (v *IssuerQuoteExecutionStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IssuerQuoteExecutionStatus(value)
	for _, existing := range AllowedIssuerQuoteExecutionStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IssuerQuoteExecutionStatus", value)
}

// NewIssuerQuoteExecutionStatusFromValue returns a pointer to a valid IssuerQuoteExecutionStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIssuerQuoteExecutionStatusFromValue(v string) (*IssuerQuoteExecutionStatus, error) {
	ev := IssuerQuoteExecutionStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IssuerQuoteExecutionStatus: valid values are %v", v, AllowedIssuerQuoteExecutionStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IssuerQuoteExecutionStatus) IsValid() bool {
	for _, existing := range AllowedIssuerQuoteExecutionStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IssuerQuoteExecutionStatus value
func (v IssuerQuoteExecutionStatus) Ptr() *IssuerQuoteExecutionStatus {
	return &v
}

type NullableIssuerQuoteExecutionStatus struct {
	value *IssuerQuoteExecutionStatus
	isSet bool
}

func (v NullableIssuerQuoteExecutionStatus) Get() *IssuerQuoteExecutionStatus {
	return v.value
}

func (v *NullableIssuerQuoteExecutionStatus) Set(val *IssuerQuoteExecutionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuerQuoteExecutionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuerQuoteExecutionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuerQuoteExecutionStatus(val *IssuerQuoteExecutionStatus) *NullableIssuerQuoteExecutionStatus {
	return &NullableIssuerQuoteExecutionStatus{value: val, isSet: true}
}

func (v NullableIssuerQuoteExecutionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuerQuoteExecutionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

