/*
Paxos API

<p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held rate quote flow.</p> <p>To test in our sandbox environment, <a href=\"https://account.sandbox.paxos.com\" target=\"_blank\">sign up</a> for an account. For more information about Paxos and our APIs, visit <a href=\"https://www.paxos.com/\" target=\"_blank\">Paxos.com</a>.</p> 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paxos

import (
	"encoding/json"
)

// checks if the OrchestrationRuleCryptoSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrchestrationRuleCryptoSource{}

// OrchestrationRuleCryptoSource struct for OrchestrationRuleCryptoSource
type OrchestrationRuleCryptoSource struct {
	AddressId *string `json:"address_id,omitempty"`
	Address *string `json:"address,omitempty"`
	Network *string `json:"network,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrchestrationRuleCryptoSource OrchestrationRuleCryptoSource

// NewOrchestrationRuleCryptoSource instantiates a new OrchestrationRuleCryptoSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrchestrationRuleCryptoSource() *OrchestrationRuleCryptoSource {
	this := OrchestrationRuleCryptoSource{}
	return &this
}

// NewOrchestrationRuleCryptoSourceWithDefaults instantiates a new OrchestrationRuleCryptoSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrchestrationRuleCryptoSourceWithDefaults() *OrchestrationRuleCryptoSource {
	this := OrchestrationRuleCryptoSource{}
	return &this
}

// GetAddressId returns the AddressId field value if set, zero value otherwise.
func (o *OrchestrationRuleCryptoSource) GetAddressId() string {
	if o == nil || IsNil(o.AddressId) {
		var ret string
		return ret
	}
	return *o.AddressId
}

// GetAddressIdOk returns a tuple with the AddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrchestrationRuleCryptoSource) GetAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.AddressId) {
		return nil, false
	}
	return o.AddressId, true
}

// HasAddressId returns a boolean if a field has been set.
func (o *OrchestrationRuleCryptoSource) HasAddressId() bool {
	if o != nil && !IsNil(o.AddressId) {
		return true
	}

	return false
}

// SetAddressId gets a reference to the given string and assigns it to the AddressId field.
func (o *OrchestrationRuleCryptoSource) SetAddressId(v string) {
	o.AddressId = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *OrchestrationRuleCryptoSource) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrchestrationRuleCryptoSource) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *OrchestrationRuleCryptoSource) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *OrchestrationRuleCryptoSource) SetAddress(v string) {
	o.Address = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *OrchestrationRuleCryptoSource) GetNetwork() string {
	if o == nil || IsNil(o.Network) {
		var ret string
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrchestrationRuleCryptoSource) GetNetworkOk() (*string, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *OrchestrationRuleCryptoSource) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given string and assigns it to the Network field.
func (o *OrchestrationRuleCryptoSource) SetNetwork(v string) {
	o.Network = &v
}

func (o OrchestrationRuleCryptoSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrchestrationRuleCryptoSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddressId) {
		toSerialize["address_id"] = o.AddressId
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrchestrationRuleCryptoSource) UnmarshalJSON(data []byte) (err error) {
	varOrchestrationRuleCryptoSource := _OrchestrationRuleCryptoSource{}

	err = json.Unmarshal(data, &varOrchestrationRuleCryptoSource)

	if err != nil {
		return err
	}

	*o = OrchestrationRuleCryptoSource(varOrchestrationRuleCryptoSource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address_id")
		delete(additionalProperties, "address")
		delete(additionalProperties, "network")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrchestrationRuleCryptoSource struct {
	value *OrchestrationRuleCryptoSource
	isSet bool
}

func (v NullableOrchestrationRuleCryptoSource) Get() *OrchestrationRuleCryptoSource {
	return v.value
}

func (v *NullableOrchestrationRuleCryptoSource) Set(val *OrchestrationRuleCryptoSource) {
	v.value = val
	v.isSet = true
}

func (v NullableOrchestrationRuleCryptoSource) IsSet() bool {
	return v.isSet
}

func (v *NullableOrchestrationRuleCryptoSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrchestrationRuleCryptoSource(val *OrchestrationRuleCryptoSource) *NullableOrchestrationRuleCryptoSource {
	return &NullableOrchestrationRuleCryptoSource{value: val, isSet: true}
}

func (v NullableOrchestrationRuleCryptoSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrchestrationRuleCryptoSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


