openapi: 3.0.0
info:
  description: |
    <p>Welcome to Paxos APIs. At Paxos, our mission is to enable the movement of any asset, any time, in a trustworthy way. These APIs serve that mission by making it easier than ever for you to directly integrate our product capabilities into your application, leveraging the speed, stability, and security of the Paxos platform.</p> <p>The documentation that follows gives you access to our Crypto Brokerage, Trading, and Exchange products. It includes APIs for market data, orders, and the held ra[...]
  title: Paxos API
  version: "2.0"
  x-logo:
    url: /docs/paxos.svg
    backgroundColor: '#FFFFFF'
    altText: Paxos logo
servers:
- description: Production
  url: https://api.paxos.com/v2
- description: Sandbox
  url: https://api.sandbox.paxos.com/v2
tags:
- description: |
    Profiles hold asset balances, and every Paxos transaction is on a particular profile.
    Depending on your integration type, Profiles may be used to reflect both corporate balances or individual user balances.
    There are two types of Profiles:
    - `DEFAULT` Profiles are system-generated.
    - `NORMAL` Profiles are created using the [Create Profile](#operation/CreateProfile) endpoint and are the only type of Profile you can create.
  name: Profiles
- description: |
    Quotes are "held rates" offered by Paxos to buy or sell assets at a specific
    price within a period of time - for example, the option to buy BTC within
    the next 30 seconds for $8,000.

    The typical Quotes workflow is as follows:

    1. Call [List Quotes](#operation/ListQuotes) to get the latest available
       quoted prices for the assets you want to buy or sell.
    1. Present the offered price to one or more end-users, with a timer
       indicating the time to expiration.
    1. If a user accepts the price, call [Create Quote Execution](#operation/CreateQuoteExecution) with the amount to buy or sell.
    1. Call [Get Quote Execution](#operation/GetQuoteExecution) to monitor
       for completion and know when the funds from the execution are available.

    It's important to show end-users the latest available price. If you cache
    prices to show them to multiple users, you should refresh the cache once
    per second.

    You can call [List Quote Executions](#operation/ListQuoteExecutions) to
    review or construct reports on quote execution activity.
  name: Quotes
- description: |
    Quote Executions buy or sell assets using a Quote obtained from
    the [Quotes](#tag/Quotes) flow.
  name: Quote Executions
- description: |
    <p>There are three types of orders: market, limit and post-only.</p>
    <p>Market orders guarantee execution at a variable price and quantity. Limit orders guarantee price and quantity at the time of execution but do not guarantee execution. Post-only is an order type that will only be placed on the order book if it is the maker side of a trade.</p>
  name: Orders
- description: |
    Market data provides various parameters of the order book and historical order data.
  name: Market Data
- description: |
    Pricing provides historical data related to charting of asset prices.

    Note: Some Pricing API markets may be unavailable for trading.
  name: Pricing
- description: |
    An Identity represents an individual person or institution entity with funds held in custody by Paxos, either directly or indirectly.
    To fully onboard an individual to Paxos, There are 2 key features that are both necessary : id verification and sanctions screening.
    Whereas to onboard an institution to Paxos, sanctions screening along with some additional documents must be submitted and then our
    compliance team will review the information and approve the identity if it is verified.

    The Identity API enables you to create and update the details associated with an identity on the Paxos platform. You can also use it to monitor the approval status of an identity to understand when they are cleared to transact.
  name: Identity
- description: |
    An institution identity can have one or more institution members. Each institution member references
    a single identity.

    Institution members are effectively immutable. In order to update properties of
    an existing member, clients should remove the existing member and add a new member with the desired state.

    To use this API, clients must have write access to the institution
    and all identities given membership. Otherwise, a client error is returned.
  name: Institution Members
- description: |
    An identity can have one or more Accounts on the Paxos platform. Accounts maintain additional context,
    such as tax status and can also be used to represent Joint Accounts where more than one identity has access
    or control over transaction activity.
  name: Accounts
- description: |
    The Account Members API allows clients to manage account members.

    Account members are effectively immutable. In order to update an account member,
    clients should remove then re-add the account member with the desired state.

    The API requires clients to have write access on the account and all identities
    associated with the account.
  name: Account Members
- description: |
    ### **NOTICE**: The following section is under a CLOSED BETA thus it is not available for all clients. Using these endpoints when outside the closed beta will result in a 403 result.

    The Identity Documents API allows clients to send documents to Paxos to validate identities
    during the KYC process. Files can be updated multiple times by re-sending the document type
    for processing.

    We currently accept the following file formats:
    - <code>pdf</code>
    - <code>jpg</code>
    - <code>png</code>

    Steps to upload a document are as follows:
    1. Send a <code>PUT</code> request to <code>/identity/identities/{id}/documents</code> to get
      the upload URL.
    1. Send your document to the provided URL via a PUT request. Take the following example using curl:
      <code>$ curl --upload-file Proof_of_residence.jpg $URI </code>

    Uploaded document metadata will be availiable via <code>GET</code> request to <code>/identity/identities/{id}/documents</code>
  name: Identity Documents
- description: |
    The Fiat Transfers API allows clients to deposit and withdraw fiat via the following Fiat Networks: Wire (Fedwire and SWIFT) and CBIT. The supported asset is USD.

    The full set of Fiat Transfers API endpoints is:
    - For Deposits:
      - [Create Fiat Deposit Instructions](#operation/CreateFiatDepositInstructions)
      - [List Fiat Deposit Instructions](#operation/ListFiatDepositInstructions)
      - [Get Fiat Deposit Instructions](#operation/GetFiatDepositInstructions)
    - For Withdrawals:
      - [Create Fiat Account](#operation/CreateFiatAccount)
      - [List Fiat Accounts](#operation/ListFiatAccounts)
      - [Get Fiat Account](#operation/GetFiatAccount)
      - [Delete Fiat Account](#operation/DeleteFiatAccount)
      - [Update Fiat Account](#operation/UpdateFiatAccount)
      - [Create Fiat Withdrawal](#operation/CreateFiatWithdrawal)
  name: Fiat Transfers
- description: |
    <p>Swap between fiat and stablecoin using <a href="#operation/CreateStablecoinConversion">Create Stablecoin Conversion</a> and check the status of a <a href="#operation/GetStablecoinConversion">single conversion</a> or retrieve a <a href="#operation/ListStablecoinConversions">list of conversions</a>.</p>
  name: Stablecoin Conversion
- description: |
    Each deposit to and withdrawal from a Paxos account is a Transfer.
    A Transfer is associated with a particular Profile, and increases or
    decreases the available balance of a single asset in that Profile.
  name: Transfers
- description: |
    All tax forms are associated to a single account_id.
    An account_id can have multiple tax forms associated with it.
    US 1099-B and 1099-Misc tax forms for the previous fiscal year will be available in February of the current calendar year.
    Previous years tax forms are also available by request.
  name: Tax Forms
- description: |
    For [Paxos Global PTE Ltd](https://help.paxos.com/hc/en-us/articles/9647005243284) users, update or reject a crypto deposit that does not contain the required [travel rule](https://help.paxos.com/hc/en-us/articles/25928845778068) information.
    Deposits with the `NEEDS_INFO` status require additional sender information before they can be processed.
    - For individuals, both first and last name are required.
    - For institutions, the institution name is required.

    If a deposit is rejected, the funds will no longer be available.
  name: Crypto Deposits
- description: |
    Use the Settlements API to facilitate simultaneous exchange of pre-funded assets. Automate a variety of use cases that require two-party approval, including net settlement of over-the-counter trades, withdrawal requests for tri-party collateral, payment requests, and bilateral settlement for marketplace end users.

    The simple request-and-approval workflow supports both one-directional and bidirectional transactions to allow a user to receive an asset (for example, send USDP) or simultaneously send and receive assets (for example, send USD and receive BTC and ETH). Only when all parties are in agreement and assets are fully funded does the Settlements API allow for change of custody. Upon completion, all settled assets are immediately available for trading, transferring, withdrawal or other supported ac[...]

    The Source Profile initiates the transaction for the Target Profile to approve. The `DIRECTION` of each asset is always relative to the Source Profile and only the owner of the Source Profile can cancel a transaction if it hasn’t been approved by the Target Profile.
  name: Settlement
paths:
  /profiles:
    get:
      description: |-
        Return the associated Profiles for the current Account.
        The paginated results default to the maximum limit of 1,000 Profiles, unless otherwise specified with the `limit` parameter.
        Every paginated response contains a `next_page` field until the last page is reached.
        Pass the `next_page` value into the `page_cursor` field of the next request to retrieve the next page of results.
      operationId: ListProfiles
      security:
      - OAuth2:
        - funding:read_profile
      summary: List Profiles
      tags:
      - Profiles
    post:
      description: Create a new profile for this account. Profiles created using this
        endpoint always have a type of `NORMAL`.
      operationId: CreateProfile
      security:
      - OAuth2:
        - funding:write_profile
      summary: Create Profile
      tags:
      - Profiles
  /profiles/{profile_id}:
    get:
      description: "Read a single profile by its UUID, or read the default profile\
        \ using the alias \"default\"."
      operationId: GetProfile
      security:
      - OAuth2:
        - funding:read_profile
      summary: Get Profile
      tags:
      - Profiles
  /profiles/{profile_id}/balances:
    get:
      description: |-
        Retrieve the Profile’s available and trading balances.
        Use query parameters to retrieve a defined set of assets.
        Omit query parameters to retrieve all asset balances.
      operationId: ListProfileBalances
      security:
      - OAuth2:
        - funding:read_profile
      summary: List Profile Balances
      tags:
      - Profiles
  /profiles/{profile_id}/balances/{asset}:
    get:
      description: Get the balance of `asset` in a profile.
      operationId: GetProfileBalance
      security:
      - OAuth2:
        - funding:read_profile
      summary: Get Profile Balance
      tags:
      - Profiles
  /sandbox/profiles/{profile_id}/deposit:
    post:
      description: |-
        Create a test deposit to fund a profile in the sandbox environment.

        Always specify `crypto_network` when making a crypto sandbox deposit. Omit the parameter when depositing fiat.

        *This functionality is only available in the sandbox environment.*
      operationId: CreateSandboxDeposit
      security:
      - OAuth2:
        - funding:read_profile
      summary: Create Sandbox Deposit
      tags:
      - Sandbox Deposits
  /identity/identities:
    get:
      description: |-
        This endpoint enables you to fetch a list of identities that you have created within the Paxos platform. You
        can use query parameters to filter the results returned by:
        - Summary Status of the Identity
        - Date created
        - Date updated

        Note that this endpoint supports pagination and returns a cursor token for fetching next pages.
      operationId: ListIdentities
      security:
      - OAuth2:
        - identity:read_identity
      summary: List Identities
      tags:
      - Identity
    post:
      description: |-
        This enables you to create a new identity within the Paxos platform. Depending upon the fields provided, the
        identity will either be person or an institution.

        - [create person identity](#create-person-identity)
        - [create institution identity](#create-institution-identity)

        A successful response indicates that the identity has been created. This does not mean that
        it has already been processed. You can use the unique ID returned within the response to check
        the approval status of the identity.

        ### Create Person Identity
        The Person identity type is used to represent individuals on the platform. Attributes of the Person identity type are recorded in the *person_details* field.

        Note that fields not listed below are forbidden in this request.

        Field | Notes
        ---|---
        person_details | Required
        metadata | Optional
        tax_details | Optional
        ref_id | Optional

        For US based identities, if the `tax_details` attribute is empty, it will be backfilled with the `cip_id` and `cip_id_country` fields from the `person_details` attribute.
        For international identities, the `tax_details` attribute must be present.

        Currently both `JUMIO` or `PASSTHROUGH` are supported for verification, but only `JUMIO` is enabled by default.

        - [create person identity with jumio verification](#automatic-id-verification-with-jumio)
        - [create person identity with passthrough verification](#automatic-id-verification-with-passthrough)

        #### Automatic ID Verification with Jumio
        To use Jumio, you must submit the fields listed below as part of the `person_details` attribute in your request.

        Field | Notes
        ---|---
        person_details.verifier_type | Required. Must be `JUMIO`
        person_details.verifier_id | Required
        person_details.address | Required

        Please note that when using this method:
        - You must ensure that the identity has already been validated by Jumio before submitting the identity to Paxos.
        - You must have previously [set the API credentials for Jumio access](#operation/SetVerifierCredentials).

        Paxos will compare the provided information with the information returned from the Jumio API.

        In the event that there is a conflict between the submitted data and the data returned from the identity provider,
        the information from the identity provider will be preferred.

        ##### Example Request
        <!--indentation does not work in swagger code blocks-->
        <pre>
        <code>
        {
        &nbsp;&nbsp;"person_details": {
        &nbsp;&nbsp;&nbsp;&nbsp;"verifier_id": "b7b77d82-e6a7-4ae9-9904-36231aedf985",
        &nbsp;&nbsp;&nbsp;&nbsp;"verifier_type": "JUMIO",
        &nbsp;&nbsp;&nbsp;&nbsp;"first_name": "John",
        &nbsp;&nbsp;&nbsp;&nbsp;"last_name": "Doe",
        &nbsp;&nbsp;&nbsp;&nbsp;"date_of_birth": "1980-01-01",
        &nbsp;&nbsp;&nbsp;&nbsp;"cip_id": "111-11-1111",
        &nbsp;&nbsp;&nbsp;&nbsp;"cip_id_type": "SSN",
        &nbsp;&nbsp;&nbsp;&nbsp;"cip_id_country": "USA",
        &nbsp;&nbsp;&nbsp;&nbsp;"nationality": "USA",
        &nbsp;&nbsp;&nbsp;&nbsp;"profession": "Engineer",
        &nbsp;&nbsp;&nbsp;&nbsp;"country_of_birth": "USA",
        &nbsp;&nbsp;&nbsp;&nbsp;"address": {
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"country": "USA",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"address1": "1 Example St",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"city": "New York",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"province": "NY",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"zip_code": "10001"
        &nbsp;&nbsp;&nbsp;&nbsp;},
        &nbsp;&nbsp;&nbsp;&nbsp;"ref_id": "33ece656-eef1-43b5-a851-b6b9099089a5"
        &nbsp;&nbsp;}
        }
        </code>
        </pre>

        #### Automatic ID Verification with Passthrough
        To use Passthrough, Paxos Compliance must first confirm your eligibility.

        Once confirmed, you can submit the fields listed below as part of the the `person_details` attribute in your request.

        | Field                                          | Notes                                                                                                     |
        |------------------------------------------------|-----------------------------------------------------------------------------------------------------------|
        | person_details.verifier_type                   | Required. Must be `PASSTHROUGH`                                                                           |
        | person_details.passthrough_verifier_type       | Required. Specifies the ID Verification provider you originally used                                      |
        | person_details.passthrough_verified_at         | Required                                                                                                  |
        | person_details.passthrough_verification_id     | Unique identifier for the underlying individual's ID verification record.                                 |
        | person_details.passthrough_verification_status | Status of the ID verification indicating whether the identity was approved or denied.                     |
        | person_details.passthrough_verification_fields | List of verification fields used by the external verifier to validate the individual's identity.          |
        | person_details.address                         | Required                                                                                                  |

        Note that the following field is forbidden in the request:
        `person_details.verifier_id`

        ##### Example Request
        <!--indentation does not work in swagger code blocks-->
        <pre>
        <code>
        {
        &nbsp;&nbsp;"person_details": {
        &nbsp;&nbsp;&nbsp;&nbsp;"verifier_type": "PASSTHROUGH",
        &nbsp;&nbsp;&nbsp;&nbsp;"passthrough_verifier_type": "JUMIO",
        &nbsp;&nbsp;&nbsp;&nbsp;"passthrough_verified_at": "2021-06-16T09:28:14Z",
        &nbsp;&nbsp;&nbsp;&nbsp;"passthrough_verification_id": "775300ef-4edb-47b9-8ec4-f45fe3cbf41f",
        &nbsp;&nbsp;&nbsp;&nbsp;"passthrough_verification_status": "APPROVED",
        &nbsp;&nbsp;&nbsp;&nbsp;"passthrough_verification_fields": ["FULL_LEGAL_NAME", "DATE_OF_BIRTH"]
        &nbsp;&nbsp;&nbsp;&nbsp;"first_name": "John",
        &nbsp;&nbsp;&nbsp;&nbsp;"last_name": "Doe",
        &nbsp;&nbsp;&nbsp;&nbsp;"date_of_birth": "1980-01-01",
        &nbsp;&nbsp;&nbsp;&nbsp;"cip_id_type": "SSN",
        &nbsp;&nbsp;&nbsp;&nbsp;"cip_id": "111-11-1111",
        &nbsp;&nbsp;&nbsp;&nbsp;"cip_id_country": "USA",
        &nbsp;&nbsp;&nbsp;&nbsp;"nationality": "USA",
        &nbsp;&nbsp;&nbsp;&nbsp;"profession": "Engineer",
        &nbsp;&nbsp;&nbsp;&nbsp;"country_of_birth": "USA",
        &nbsp;&nbsp;&nbsp;&nbsp;"address": {
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"country": "USA",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"address1": "1 Example St",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"city": "New York",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"province": "NY",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"zip_code": "10001"
        &nbsp;&nbsp;&nbsp;&nbsp;},
        &nbsp;&nbsp;&nbsp;&nbsp;"ref_id": "33ece656-eef1-43b5-a851-b6b9099089a5"
        &nbsp;&nbsp;}
        }
        </code>
        </pre>

        ### Create Institution Identity
        Institution identities are used to represent all non-person entities.
        Details for institution identity type are recorded in `institution_details`. An institution identity also has `institution_members` associated with it. This defines persons or other entities that have some relationship to the institution.

        We support the following types and sub-types of institutions. Note that all institution types listed do share some common validations that can also be found below.

        #### Supported Institution Types

        institution_type | Supported institution_member roles | Notes
        ---| ---| ---
        `TRUST` | `BENEFICIAL_OWNER`<br>`BENEFICIARY`<br>`GRANTOR`<br>`TRUSTEE` | [See Trusts](#trust-institutions-requirement)
        `CORPORATION`<br>`LLC`<br>`PARTNERSHIP` | `ACCOUNT_OPENER`<br>`AUTHORIZED_USER`<br>`BENEFICIAL_OWNER`<br>`MANAGEMENT_CONTROL_PERSON` | [See other Institutions](#institutions-requirement)

        #### Industry Type to Institution Subtypes Mapping
        institution_sub_type | industry
        ---| ---
        `ACCOMMODATION_FOOD_SERVICES` |   Food or Beverage Services
        `ADMINISTRATIVE_SUPPORT_WASTE_MANAGEMENT_REMEDIATION_SERVICES` |  Administrative and Support Services
        `ADULT_ENTERTAINMENT` | Adult Entertainment / Pornography
        `AGRICULTURE_FORESTRY_FISHING_HUNTING` | Agriculture
        `ARTS_ENTERTAINMENT_RECREATION` | Arts, Entertainment, and Recreation
        `AUCTIONS` | Auction Houses / Art Galleries
        `AUTOMOBILES` | Automobiles / Automotives
        `BLOCKCHAIN` | Blockchain Technology
        `CONSTRUCTION` | Construction
        `CRYPTO` | Crypto Services and Products (Mining, Exchange, Broker)
        `DRUGS` | Illicit Drugs / Drug Paraphernalia
        `E_COMMERCE` | E-Commerce
        `EDUCATIONAL_SERVICES` | Educational Services
        `EXPORT_IMPORT` | Export / Import Companies
        `FINANCE_INSURANCE` | Other Financial & Insurance Services (Not Referenced Elsewhere)
        `FINANCIAL_INSTITUTION` | Financial Institution
        `GAMBLING` | Gaming, Gambling, Casinos, or Sports Betting
        `HEALTH_CARE_SOCIAL_ASSISTANCE` | Health Care and Social Assistance
        `HEDGE_FUND` | Pooled Investment Vehicle / Investment Fund / Hedge Fund
        `INFORMATION` | Information, Communications, and Media
        `INSURANCE` | Insurance
        `INVESTMENT` | Investment
        `MANAGEMENT_OF_COMPANIES_ENTERPRISES` | Management of Companies & Enterprises (Holding Companies)
        `MANUFACTURING` | Manufacturing
        `MARKET_MAKER` | Market Maker / Proprietary Trading
        `MINING` | Oil & Gas
        `MONEY_SERVICE_BUSINESS` | Money Services Business / Money Transmitters (including ATMs)
        `NON_PROFIT` | Non-Profit, Charity or Political Organizations
        `OTHER_SERVICES` | Other
        `PRECIOUS_METALS` | Jewelry or Precious Metals (Mining, Transportation, Dealing or Retail)
        `PROFESSIONAL_SCIENTIFIC_TECHNICAL_SERVICES` | Professional Services (Consulting, Legal, Accounting, etc.)
        `PUBLIC_ADMINISTRATION` | Public or Government Services
        `RANSOMWARE` | Ransomware / Facilitators of Ransomware Transactions
        `REAL_ESTATE_RENTAL_LEASING` | Real Estate and Rental and Leasing
        `REGISTERED_INVESTMENT_ADVISOR` | Registered Investment Advisor
        `RETAIL_TRADE` | Retail Trade
        `SHELL_BANK` | Shell Banks or Shell Companies
        `STO_ISSUER` | Security Token Offering (STO) Issuer
        `TRANSPORTATION_WAREHOUSING` | Transportation and Services
        `TRAVEL_TRANSPORT` | Travel, Accomodation or Transport
        `UTILITIES` | Utilities
        `WEAPONS` | Weapons or Arms (Manufacturing, Sales or Transportation)
        `WHOLESALE_TRADE` | Wholesale Trade

        Notes:
        - `INVESTMENT` is only supported by the institution type `TRUST`.
        - All other subtypes are only supported by types `CORPORATION`, `LLC` and `PARTNERSHIP`.

        #### Prohibited Institution Subtypes

        Paxos prohibits certain types of business activity (“Prohibited Businesses”) in accordance with its Compliance policies.
        The following non-exhaustive list is representative of the type of activity that Paxos prohibits on its platform.
        By creating a Paxos Identity, Paxos customers agree not to use Paxos services in connection with any of the following Prohibited Businesses.

        - `ADULT_ENTERTAINMENT`
        - `DRUGS`
        - `RANSOMWARE`
        - `SHELL_BANK`
        - `WEAPONS`

        #### Shared Validations Across All Institution Types

        Field | Notes
        ---|---
        cip_id | One of EIN, REGISTRATION_NUMBER, SSN, ITIN. SSN and ITIN are only supported for passthrough/revocable entities.
        tax_details | Automatically populated if the cip_id_type is SSN, ITIN or EIN.
        tax_details_not_required | Can be set for non-US institutions where tax details are not required.
        metadata | Optional
        ref_id | Optional

        #### Specifying Institution Members and Their Roles

        Field | Notes
        ---|---
        identity_id | Required
        roles | Required.
        ownership | Optional. Must be between 0 and 100
        position | Optional

        Note
        See supported institution types for details on which roles are supported by which institution type.

        #### Fields Required for Trusts

        Type | Fields
        ---|---
        Required | name, cip_id, cip_id_type, cip_id_country, institution_type, institution_sub_type, business_address, govt_registration_date
        Optional | phone_number, email, incorporation_address, regulation_status, trading_type, listed_exchange, ticker_symbol, parent_institution_name, regulator_jurisdiction, regulator_name, regulator_register_number

        Notes
        Fields not listed are forbidden in the request. `institution_type` must be set to TRUST. `institution_sub_type` must be set to Investment.
        `incorporation_address` is required for Trusts where their cip_id_type is not SSN or ITIN.

        ##### Example Request for a Trust
        <!--indentation does not work in swagger code blocks-->
        <pre>
        <code>
        {
        &nbsp;&nbsp;"institution_members": [{
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"identity_id": "33ece656-eef1-43b5-a851-b6b9099089a5",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"roles": ["GRANTOR"]
        &nbsp;&nbsp;&nbsp;&nbsp;},
        &nbsp;&nbsp;&nbsp;&nbsp;{
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"identity_id": "44ece656-eef1-43b5-a851-b6b9099089a6",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"roles": ["TRUSTEE"]
        &nbsp;&nbsp;&nbsp;&nbsp;}],
        &nbsp;&nbsp;"institution_details": {
        &nbsp;&nbsp;&nbsp;&nbsp;"name": "Trust A",
        &nbsp;&nbsp;&nbsp;&nbsp;"business_address": {
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"country": "United States",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"address1": "1 Example St",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"city": "New York",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"province": "NY",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"zip_code": "10001"
        &nbsp;&nbsp;&nbsp;&nbsp;},
        &nbsp;&nbsp;&nbsp;&nbsp;"email": "institution_a@acorp.com",
        &nbsp;&nbsp;&nbsp;&nbsp;"institution_type": "CORPORATION",
        &nbsp;&nbsp;&nbsp;&nbsp;"institution_sub_type": "HEDGE_FUND",
        &nbsp;&nbsp;&nbsp;&nbsp;"cip_id": "11-1111111",
        &nbsp;&nbsp;&nbsp;&nbsp;"cip_id_type": "EIN",
        &nbsp;&nbsp;&nbsp;&nbsp;"cip_id_country": "USA",
        &nbsp;&nbsp;&nbsp;&nbsp;"govt_registration_date": "2021-04-14T00:00:00Z",
        &nbsp;&nbsp;&nbsp;&nbsp;"incorporation_address": {
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"country": "United States",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"address1": "1 Example St",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"city": "New York",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"province": "NY",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"zip_code": "10001"
        &nbsp;&nbsp;&nbsp;&nbsp;},
        &nbsp;&nbsp;&nbsp;&nbsp;"regulation_status": "US_REGULATED",
        &nbsp;&nbsp;&nbsp;&nbsp;"trading_type": "PUBLIC",
        &nbsp;&nbsp;&nbsp;&nbsp;"listed_exchange": "NASDAQ",
        &nbsp;&nbsp;&nbsp;&nbsp;"ticker_symbol": "ABC",
        &nbsp;&nbsp;&nbsp;&nbsp;"regulator_name": "SEC",
        &nbsp;&nbsp;&nbsp;&nbsp;"regulator_jurisdiction": "USA",
        &nbsp;&nbsp;&nbsp;&nbsp;"regulator_register_number": "111-111111"
        &nbsp;&nbsp;}
        }
        </code>
        </pre>

        #### Fields Required for Institutions (excluding Trusts and Registered Investment Advisors)

        Type | Fields
        ---|---
        Required | name, cip_id, cip_id_type, cip_id_country, institution_type, institution_sub_type, business_address, incorporation_address, govt_registration_date, regulation_status, trading_type
        Optional | phone_number, email, listed_exchange, ticker_symbol, parent_institution_name, regulator_jurisdiction, regulator_name, regulator_register_number

        #### Creating Financially Regulated Institutions
        Please refer to the following table for creating institutions which are financially regulated.

        regulation_status | Notes
        ---|---
        US_REGULATED | Institution financially regulated in the US
        INTL_REGULATED | Institution financially regulated by an international entity
        NON_REGULATED | Non-financially regulated institution

        Note that each category of `regulation_status` then has additional validations tied to `trading type` and other required fields.

        regulation_status | trading_type | fields required | Notes
        ---|---|---|---
        US_REGULATED | PRIVATE | regulator_name, regulator_jurisdiction, regulator_register_number | Not publicly traded
        US_REGULATED | PUBLIC | listed_ exchange, ticker_symbol, regulator_name, regulator_jurisdiction, regulator_register_number | Publicly traded
        US_REGULATED | PUBLICLY_TRADED_SUBSIDIARY | listed_exchange, ticker_symbol, regulator_name, regulator_jurisdiction, regulator_register_number, parent_institution_name | Subsidiary of a publicly traded company
        INTL_REGULATED | PRIVATE | regulator_name, regulator_jurisdiction, regulator_register_number | Not publicly traded
        INTL_REGULATED | PUBLIC | listed_ exchange, ticker_symbol, regulator_name, regulator_jurisdiction, regulator_register_number | Publicly traded
        INTL_REGULATED | PUBLICLY_TRADED_SUBSIDIARY | listed_exchange, ticker_symbol, regulator_name, regulator_jurisdiction, regulator_register_number, parent_institution_name | Subsidiary of a publicly traded company
        NON_REGULATED | PRIVATE | PRIVATE | Not publicly traded
        NON_REGULATED | PUBLIC | listed_exchange, ticker_symbol | Publicly traded

        #### Fields required for Registered Investment Advisors (RIA)

        RIAs are a special sub-type of Institution. Usage of this sub-type requires prior authorization and approval from Paxos.

        Notes
        `institution_sub_type` must be set to REGISTERED_INVESTMENT_ADVISOR. The list of required and optional fields below varies slightly from other supported institutions
        while certain fields are optional (e.g. trading_type), if they are specified in the request, their input will been validated

        Type | Fields
        ---|---
        Required | name, cip_id, cip_id_type, cip_id_country, institution_type, institution_sub_type, business_address, regulation_status, regulator_jurisdiction, regulator_name, regulator_register_number
        Optional | phone_number, email, listed_exchange, ticker_symbol, parent_institution_name, incorporation_address, govt_registration_date, trading_type
      operationId: CreateIdentity
      security:
      - OAuth2:
        - identity:write_identity
      summary: Create Identity
      tags:
      - Identity
  /identity/identities/{identity_id}/documents:
    get:
      description: This endpoint enables you to get a list of all documents associated
        with an identity.
      operationId: ListIdentityDocuments
      security:
      - OAuth2:
        - identity:read_identity
      summary: List Identity Documents
      tags:
      - Identity Documents
    put:
      description: |-
        This endpoint enables you to receive a URL to upload a document to Paxos.
        When uploading a document one must specify the document type, you will receive a
        URL to upload a document into using a POST request. (see curl documentation)
      operationId: DocumentUpload
      security:
      - OAuth2:
        - identity:write_identity
      summary: Document Upload
      tags:
      - Identity Documents
  /identity/identities/{id}:
    get:
      description: |-
        Get an identity by ID. By default, the identity details (person_details or institution_details) will not be returned.
        Set `?include_details=true` to receive them in the response. For institution type identities,
        members will not be returned in the default response. Set `?include_institution_members=true` to get the members.

        An identity is allowed to transact on the Paxos platform when `summary_status` is `"APPROVED"`.
      operationId: GetIdentity
      security:
      - OAuth2:
        - identity:read_identity
      summary: Get Identity
      tags:
      - Identity
    put:
      description: |-
        This enables you to update an existing identity with new information. Please note that:
        - Updating any field other than `set_user_disabled`, `metadata`, `ref_id`, or `is_merchant` will transition the identity to a PENDING status.
        This will restrict the identity until it has been re-verified.
        - Setting `set_user_disabled` to `true` will disable the identity, limiting its ability to be used within
        the Paxos platform.
        - Setting `is_merchant` to `true` will indicate that this identity is a merchant.
        - Details of the identity can be updated by providing `person_details` or `institution_details` depending upon the type.
        - You can add, update or remove tax_details by providing the `tax_details` list. The tax_details will be updated to exactly
        comprise the given list

        Note: Identity conversion from person to institution type or vice-versa is not permitted.
      operationId: UpdateIdentity
      security:
      - OAuth2:
        - identity:write_identity
      summary: Update Identity
      tags:
      - Identity
  /identity/identities/{id}/retry-id-verification:
    post:
      description: |-
        This endpoint enables you to retry the ID verification for an identity with verifier type PAXOS
        by setting the id verification status to PENDING and returning a new id verification URL.
      operationId: RetryIdVerification
      security:
      - OAuth2:
        - identity:write_identity
      summary: Retry Id Verification
      tags:
      - Identity Credentials
  /identity/verifier-credentials:
    post:
      description: |-
        Set the credentials used for automatic verification with a supported identity provider. This applies for only
        `PERSON` type identities.

        ### Supported Identity Providers

        Provider | verifier_type | Verifier Scope
        ---|---|---
        Jumio | JUMIO | Retrieve & Delete
      operationId: SetVerifierCredentials
      security:
      - OAuth2:
        - identity:write_verifier_credentials
      summary: Set Verifier Credentials
      tags:
      - Identity Credentials
  /identity/institution-members:
    post:
      description: |-
        Add one or more institution members to a given institution.

        Adding new members doesn't affect existing members. For example, if an institution has three
        members, and adds two members using this API, then the institution would end up with five total members.

        For details on the properties that can be specified when creating institution members,
        see [Specifying Institution Members and Their Roles](#specifying-institution-members-and-their-roles).
      operationId: AddInstitutionMembers
      security:
      - OAuth2:
        - identity:write_identity
      summary: Add Institution Members
      tags:
      - Institution Members
  /identity/institution-members/{id}:
    delete:
      description: Removes an institution member from an institution.
      operationId: DeleteInstitutionMember
      security:
      - OAuth2:
        - identity:write_identity
      summary: Remove Institution Member
      tags:
      - Institution Members
  /identity/accounts:
    get:
      description: |-
        List accounts with pagination. Every response will contain a `next_page` field,
        as long as the end of the list has not been reached. Pass this value into the `page_cursor` field of the next request
        to retrieve the next page of results.
      operationId: ListAccounts
      security:
      - OAuth2:
        - identity:read_account
      summary: List Accounts
      tags:
      - Accounts
    post:
      description: |-
        Create an account for a given identity, via the `identity_id` field.
        This identity is the primary owner of the account for all tax-related purposes.

        To track user balances using Paxos [Profiles](#tag/Profiles), use `create_profile=true` when creating the account.
        Once an account has been created, it is not possible to associate it with a [Profile](#tag/Profiles).

        ### Account Members

        In addition to the primary owner, other identities may be associated with the account, by using `members`.
        The identity on the account is treated as a BENEFICIAL_OWNER.

        To add a financial advisor to an account, add a member with the FINANCIAL_ADVISOR role.

        #### Example
        This example request creates a joint account for John and Jane Doe. John has identity_id=82c338f4-3cb7-4d9b-be2a-4b077c82ee3a,
        and Jane has identity_id=0f5d8475-33f3-4ebd-88a0-66dedc2581c1. John is the primary owner of the account for tax-purposes, but Jane
        is a full beneficial owner.

        Additionally, this account has an associated financial advisor with identity_id=0d26f878-298e-4d47-81be-cdf4e982a3d3.

        <!--indentation does not work in swagger code blocks-->
        <pre>
        <code>
        {
        &nbsp;&nbsp;"account": {
        &nbsp;&nbsp;&nbsp;&nbsp;"identity_id": "82c338f4-3cb7-4d9b-be2a-4b077c82ee3a",
        &nbsp;&nbsp;&nbsp;&nbsp;"members": [{
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"identity_id": "0f5d8475-33f3-4ebd-88a0-66dedc2581c1",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"roles": ["BENEFICIAL_OWNER"]
        &nbsp;&nbsp;&nbsp;&nbsp;}, {
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"identity_id": "0d26f878-298e-4d47-81be-cdf4e982a3d3",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"roles": ["FINANCIAL_ADVISOR"]
        &nbsp;&nbsp;&nbsp;&nbsp;}]
        &nbsp;&nbsp;}
        }
        </code>
        </pre>

        ### Fields

        Any fields not listed are forbidden in this request.

        Field | Notes
        ---|---
        identity_id | Required
        description | Optional
        metadata | Optional
        ref_id | Optional
        members | Optional
      operationId: CreateAccount
      security:
      - OAuth2:
        - identity:write_account
      summary: Create Account
      tags:
      - Accounts
    put:
      description: |-
        This enables you to update an existing account with new information. Please refer to the following
        table for fields that can be updated via this endpoint.

        Field | Notes
        ---|---
        account.id | Required
        account.description | Optional
        account.ref_id | Optional
        account.metadata | Optional. This will overwrite any existing metadata added to the account.
        account.members | Optional. The only roles that can be added/removed are `FINANCIAL_ADVISOR` or `AUTHORIZED_USER.` You must always specify the full members object as we do not currently support differential member updates.
        set_user_disabled | Optional. Setting this to `true` will disable the account, limiting its ability to be used within the Paxos platform.

        #### Example Requests
        #### Disabling an account

        <!--indentation does not work in swagger code blocks-->
        <pre>
        <code>
        {
        &nbsp;&nbsp;"set_user_disabled": true,
        &nbsp;&nbsp;"account": {
        &nbsp;&nbsp;&nbsp;&nbsp;"id": "82c338f4-3cb7-4d9b-be2a-4b077c82ee3a",
        &nbsp;&nbsp;&nbsp;&nbsp;"description": "Account Description",
        &nbsp;&nbsp;&nbsp;&nbsp;"ref_id": "82c338f4-3cb7",
        &nbsp;&nbsp;}
        }
        </code>
        </pre>

        ### Adding an account member
        To retain the existing account members and add a new account member, the `members` field must contain the existing account members and the
        new member. The below example adds an `AUTHORIZED_USER` to the account.

        In order to add account members while leaving existing account members unaffected, clients
        should use the [Add Account Members](#operation/AddAccountMembers) API.

        <!--indentation does not work in swagger code blocks-->
        <pre>
        <code>
        {
        &nbsp;&nbsp;"account": {
        &nbsp;&nbsp;&nbsp;&nbsp;"id": "82c338f4-3cb7-4d9b-be2a-4b077c82ee3a",
        &nbsp;&nbsp;&nbsp;&nbsp;"members": [{
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"identity_id": "0f5d8475-33f3-4ebd-88a0-66dedc2581c1",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"roles": ["BENEFICIAL_OWNER"]
        &nbsp;&nbsp;&nbsp;&nbsp;}, {
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"identity_id": "0d26f878-298e-4d47-81be-cdf4e982a3d3",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"roles": ["FINANCIAL_ADVISOR"]
        &nbsp;&nbsp;&nbsp;&nbsp;}, {
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"identity_id": "012k23eb-298e-4d47-81be-cdf4e982a3d3",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"roles": ["AUTHORIZED_USER"]
        &nbsp;&nbsp;&nbsp;&nbsp;}]
        &nbsp;&nbsp;}
        }
        </code>
        </pre>

        ### Removing an account member
        To remove an existing account member and retain other needed members, the `members` field must contain
        the existing account members without the account member you'd like to remove. The below example removes an `AUTHORIZED_USER` from the account.

        Note, this API requires the `members` array to have at least one element. In order to delete all members
        from an account, clients should use the [Delete Account Member](#operation/DeleteAccountMember) API.

        <!--indentation does not work in swagger code blocks-->
        <pre>
        <code>
        {
        &nbsp;&nbsp;"account": {
        &nbsp;&nbsp;&nbsp;&nbsp;"id": "82c338f4-3cb7-4d9b-be2a-4b077c82ee3a",
        &nbsp;&nbsp;&nbsp;&nbsp;"members": [{
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"identity_id": "0f5d8475-33f3-4ebd-88a0-66dedc2581c1",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"roles": ["BENEFICIAL_OWNER"]
        &nbsp;&nbsp;&nbsp;&nbsp;}]
        &nbsp;&nbsp;}
        }
        </code>
        </pre>

        ### Updating an account members' roles
        To update an account members' roles, the `members` field must contain all the existing members with their roles along
        with the additional role that you'd like to add or remove. The below example adds the `FINANCIAL_ADVISOR` role to an member that is already a `BENEFICIAL_OWNER`.

        <!--indentation does not work in swagger code blocks-->
        <pre>
        <code>
        {
        &nbsp;&nbsp;"account": {
        &nbsp;&nbsp;&nbsp;&nbsp;"id": "82c338f4-3cb7-4d9b-be2a-4b077c82ee3a",
        &nbsp;&nbsp;&nbsp;&nbsp;"members": [{
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"identity_id": "0f5d8475-33f3-4ebd-88a0-66dedc2581c1",
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"roles": ["BENEFICIAL_OWNER", "FINANCIAL_ADVISOR"]
        &nbsp;&nbsp;&nbsp;&nbsp;}]
        &nbsp;&nbsp;}
        }
        </code>
        </pre>
      operationId: UpdateAccount
      security:
      - OAuth2:
        - identity:write_account
      summary: Update Account
      tags:
      - Accounts
  /identity/accounts/{id}:
    get:
      operationId: GetAccount
      security:
      - OAuth2:
        - identity:read_account
      tags:
      - Accounts
  /identity/account-members:
    post:
      description: |-
        Add one or more account members to a given account.

        The account members added by this API do not affect existing account members. For example,
        if an account has two members, and one member is added using this API, then the account will
        end up with three members.

        For more information on properties of account members, see [Account Members](#account-members).
      operationId: AddAccountMembers
      security:
      - OAuth2:
        - identity:write_account
      summary: Add Account Members
      tags:
      - Account Members
  /identity/account-members/{id}:
    delete:
      description: Removes an account member from an account.
      operationId: DeleteAccountMember
      security:
      - OAuth2:
        - identity:write_account
      summary: Remove Account Member
      tags:
      - Account Members
  /identity/identities/{id}/sandbox-status:
    put:
      description: |-
        Set the various statuses for the given Identity. To enable the Person Identity to transact,
        set both `id_verification_status` and `sanctions_verification_status` to `"APPROVED"`.
        To enable the Institution to transact, set both `sanctions_verification_status` to `"APPROVED"`.
        This endpoint also allows you to set the statuses for `document_verification_status` and
        `additional_screening_status`
      operationId: SandboxSetIdentityStatus
      security:
      - OAuth2:
        - identity:write_identity
      summary: Sandbox Set Identity Status
      tags:
      - Sandbox Identity
  /all-markets/prices:
    get:
      description: |-
        Retrieve current prices, as well as 24 hour prior (yesterday) prices, for the specified markets.
        Any single market that failed to be retrieved is excluded from the response.
      operationId: ListPrices
      summary: List Prices
      tags:
      - Pricing
  /all-markets/ticker:
    get:
      description: |-
        Retrieves order book statistics of the exchange for all markets over the last 24 hours and from midnight UTC until current time.

        Please note: List Tickers displays pricing from external venues when the itBit exchange is not available.
      operationId: ListTickers
      summary: List Tickers
      tags:
      - Pricing
  /executions:
    get:
      description: |-
        Retrieves full details of underlying executions with optional filters.
        Notes:
        - This endpoint returns a maximum of 1000 items per page.
        - Filtering options are `account_id`, `profile_id` or neither (all executions).
      operationId: ListExecutions
      security:
      - OAuth2:
        - exchange:read_order
      summary: List Executions
      tags:
      - Orders
  /markets:
    get:
      description: Retrieves the set of current available markets for trading with
        details.
      operationId: ListMarkets
      summary: List Markets
      tags:
      - Market Data
  /markets/{market}/historical-prices:
    get:
      description: |-
        Retrieves a set of average prices at a certain increment of time for the requested market.
        This endpoint is suitable for retrieving historical average price trends where price precision, execution, and
        other detailed information is not required.
        To control the count, use either  `increment` or `max_data_points`.
        List Historical Prices returns an error when an unexpected value is given, or when `increment` and
         `max_data_points` are both given or omitted.

        When `range.begin` is omitted, the first data point shows the mid price, the average of the order book best bid
         and ask price, or the earliest available date. It is possible to set `range.begin` to a future date without error.

        When `range.end` is omitted, the last data point will display current mid price (average of order book best bid
         and best ask) at the request timestamp. It is possible to set `range.end` to a future date without error.

        When `pagination.limit` is omitted, the pagination limit will default to return the first 100 items.
        If the pagination limit is set, the API will return up to the limit in one response. The pagination limit max is 1,000.

        Time-series items are returned in chronological (ascending) order. All timestamps are in UTC.
      operationId: ListHistoricalPrices
      security:
      - OAuth2:
        - exchange:historical_prices
      summary: List Historical Prices
      tags:
      - Pricing
  /markets/{market}/order-book:
    get:
      description: Retrieves the full list of bids and asks of the order book at individual
        price levels with resting quantities per level.
      operationId: GetOrderBook
      summary: Get Order Book
      tags:
      - Market Data
  /markets/{market}/recent-executions:
    get:
      description: Retrieves the list of 2000 most recent executions by all users
        to occur in the order book.
      operationId: ListRecentExecutions
      summary: List Recent Executions
      tags:
      - Market Data
  /markets/{market}/ticker:
    get:
      description: Retrieves order book statistics of the exchange over the last 24
        hours and from midnight UTC until current time.
      operationId: GetTicker
      summary: Get Ticker
      tags:
      - Market Data
  /orders:
    get:
      description: |-
        Retrieves full details of orders associated with a Profile ID, with optional filters.

        - Historical data prior to May 16, 2022 is unavailable.
        - Pagination Limit has a max of 1000. Pagination Offset is now deprecated and nonfunctional.
        - Filtering options are `account_id`, `profile_id` or neither (all orders).
      operationId: ListOrders
      security:
      - OAuth2:
        - exchange:read_order
      summary: List Orders
      tags:
      - Orders
  /profiles/{profile_id}/executions:
    get:
      description: |-
        Retrieves full details of underlying executions for a profile id with optional filters.
        If pagination details are not set the response will default to 20 items. Additionally, this endpoint will return a maximum of 500 items per page.
      operationId: ListProfileExecutions
      security:
      - OAuth2:
        - exchange:read_order
      summary: List Executions
      tags:
      - ExchangePublic
  /profiles/{profile_id}/orders:
    get:
      description: |-
        Retrieves full details of orders associated with a profile id with optional filters.

        Notes:
        - Pagination Limit has a max of 1000 and Pagination Offset a max of 10000. If a larger Offset is needed, please contact support.
      operationId: ListProfileOrders
      security:
      - OAuth2:
        - exchange:read_order
      summary: List Orders
      tags:
      - ExchangePublic
    post:
      description: |-
        For limit orders, create an order for buying or selling an asset:

        - To buy, set `side = BUY` and set `base_amount` to the crypto amount you want to buy.
        - To sell, set `side = SELL` and set `base_amount` to the crypto amount you want to sell.

        For market orders, create an order for buying or selling an asset:

        - To buy, set `side = BUY` and set `quote_amount` to the dollar amount you want to spend.
        - To sell, set `side = SELL` and set `base_amount` to the crypto amount you want to sell.

        There are five types of orders:

        - Limit Orders: Buy or sell at a specified price or better. Execution not guaranteed. Taker orders will be rejected if price deviates 15% from midpoint.
        - Post-Only Limit Orders: have the same properties as Limit Orders, but get rejected if they cross the orderbook.
        - Market Orders: Operate as Immediate or Cancel (IOC) orders. Price is variable, executes at best available price at time of order.
        - Stop Market Orders: Will convert to a market sell order with the specified quantity when the stop price is hit. The stop price does not guarantee that it will be executed at that price. Market conditions (price) might change between the order being triggered and order being executed. Currently only sell stop loss orders are supported.
        - Stop Limit Orders: have a Stop Price which when hit, will convert to a limit sell order that will be executed at a specified price (or better)

        Maximum notional order size by type:

        Order Type | Market  | Maximum Notional Value (USD)
        ---------- | ------- | ----------------------------
        Market     | all     | 500,000
        Limit      | BTCUSD  | 1,500,000
        Limit      | ETHUSD  | 1,500,000
        Limit      | other   | 1,000,000
      operationId: CreateOrder
      security:
      - OAuth2:
        - exchange:write_order
      summary: Create Order
      tags:
      - Orders
  /profiles/{profile_id}/orders/{id}:
    delete:
      description: |-
        Submits a cancellation request. A response indicates that the request has been acknowledged and provides no
        guarantee the order has been cancelled.
      operationId: CancelOrder
      security:
      - OAuth2:
        - exchange:write_order
      summary: Cancel Order
      tags:
      - Orders
    get:
      description: |-
        Retrieves the current state of an order.
        - Historical data prior to May 16, 2022 is unavailable.
      operationId: GetOrder
      security:
      - OAuth2:
        - exchange:read_order
      summary: Get Order
      tags:
      - Orders
  /profiles/{profile_id}/quote-executions:
    get:
      description: List quote executions within a particular profile.
      operationId: ListQuoteExecutions
      security:
      - OAuth2:
        - exchange:read_quote_execution
      summary: List Quote Executions
      tags:
      - Quote Executions
    post:
      description: |-
        Execute on a quote for buying or selling an asset.

        The side, market, and guaranteed price of the execution are specified by the quote
        with ID `quote_id`.

        The amount to buy or sell must be specified in either fiat or crypto by setting
        exactly one of:
         - `base_amount` to specify the amount of crypto to buy or sell.
         - `quote_amount` to specify the amount of fiat to spend or acquire.

        An otherwise-valid request to create a quote execution may fail with the following
        types of errors:
         - [Expired](https://developer.paxos.com/docs/v2/problems/expired) if the quote
           with ID `quote_id` has expired.
         - [Insufficient Funds](https://developer.paxos.com/docs/v2/problems/insufficient-funds)
           if the profile with ID `profile_id` has insufficient available balance to
           fund the execution.
         - [Rejected](https://developer.paxos.com/docs/v2/problems/rejected) if extreme
           market conditions (e.g. a very large price swing) have invalidated the quote.
         - [Already Exists](https://developer.paxos.com/docs/v2/problems/already-exists)
           if a Quote Execution with the same `ref_id` has already been created.
      operationId: CreateQuoteExecution
      security:
      - OAuth2:
        - exchange:write_quote_execution
      summary: Create Quote Execution
      tags:
      - Quote Executions
  /profiles/{profile_id}/quote-executions/{id}:
    get:
      description: Get an existing quote execution for buying or selling an asset.
      operationId: GetQuoteExecution
      security:
      - OAuth2:
        - exchange:read_quote_execution
      summary: Get Quote Execution
      tags:
      - Quote Executions
  /quotes:
    get:
      description: |-
        List quotes for buying or selling assets. By default, the list will
        include the latest available quotes for both buying and selling all supported
        assets.

        Each quote is valid until `expires_at`, and can be executed on by
        calling [Create Quote Execution](#operation/CreateQuoteExecution).

        Multiple calls to list quotes in quick succession may return the same quote
        values. Paxos currently issues new quotes at most once per second.
      operationId: ListQuotes
      security:
      - OAuth2:
        - exchange:read_quote
      summary: List Quotes
      tags:
      - Quotes
  /sandbox/fiat-deposits:
    post:
      description: |-
        Initiate a test fiat deposit in the sandbox environment.

        The deposit will be processed based on `memo_id` from a previous Fiat Deposit Instructions response.

        *This functionality is only available in the sandbox environment.*
      operationId: InitiateSandboxFiatDeposit
      security:
      - OAuth2:
        - transfer:write_sandbox_fiat_deposit
      summary: Initiate Sandbox Fiat Deposit
      tags:
      - Sandbox Fiat Transfers
  /transfer/crypto-deposits/{id}/reject:
    post:
      description: |-
        Reject a crypto deposit which is waiting for required travel rule information about the originator address.
        If the rejected deposit has any status other than `NEEDS_INFO`, the request will return an error.
        Only the creator of the crypto deposit can reject it.
      operationId: RejectCryptoDeposit
      security:
      - OAuth2:
        - transfer:reject_crypto_deposit
      summary: Reject Crypto Deposit
      tags:
      - Crypto Deposits
  /transfer/crypto-deposits/{id}/update:
    post:
      description: |-
        Crypto deposits that do not meet the minimum travel rule requirements are blocked.
        To update a crypto deposit, provide the required travel rule information about the originator address.
      operationId: UpdateCryptoDeposit
      security:
      - OAuth2:
        - transfer:update_crypto_deposit
      summary: Update Crypto Deposit
      tags:
      - Crypto Deposits
  /transfer/crypto-withdrawals:
    post:
      description: Withdraw a cryptocurrency asset to a specified destination address.
      operationId: CreateCryptoWithdrawal
      security:
      - OAuth2:
        - transfer:write_crypto_withdrawal
      summary: Create Crypto Withdrawal
      tags:
      - Crypto Withdrawals
  /transfer/deposit-addresses:
    get:
      description: "List all deposit addresses, optionally filtering and paging the\
        \ results."
      operationId: ListDepositAddresses
      security:
      - OAuth2:
        - transfer:read_deposit_address
      summary: List Deposit Addresses
      tags:
      - Deposit Addresses
    post:
      description: Create a deposit address on a blockchain network for depositing
        to a profile.
      operationId: CreateDepositAddress
      security:
      - OAuth2:
        - transfer:write_deposit_address
      summary: Create Deposit Address
      tags:
      - Deposit Addresses
  /transfer/fees/crypto-withdrawal:
    post:
      description: |-
        Get a guaranteed fee for the given currency, valid for a period of time.
        Specify exactly one of `amount` or `total`, otherwise an error is returned.

        The [Create Crypto Withdrawal](#operation/CreateCryptoWithdrawal) request that uses the guaranteed fee endpoint
        must specify an `amount` less than or equal to the guaranteed fee `amount`, otherwise the withdrawal is rejected.
      operationId: CreateCryptoWithdrawalFee
      security:
      - OAuth2:
        - fee:write_crypto_withdrawal_fee
      summary: Create Crypto Withdrawal Fee
      tags:
      - Fees
  /transfer/fiat-accounts:
    get:
      description: |-
        List all Fiat Accounts, optionally filtering and paging the results.
        The response includes an abbreviated `FiatAccount` object:

        - Beneficiary name and address details are excluded.
        - Only the last four (**4**) digits of the account number are included.

        Use [Get Fiat Account](#operation/GetFiatAccount) to retrieve the complete `FiatAccount` object.

        The paginated results default to the maximum limit of 1,000 Fiat Accounts, unless otherwise specified with the `limit` parameter.
        Every paginated response contains a `next_page` field until the last page is reached.
        Pass the `next_page` value into the `page_cursor` field of the next request to retrieve the next page of results.
      operationId: ListFiatAccounts
      security:
      - OAuth2:
        - transfer:read_fiat_account
      summary: List Fiat Accounts
      tags:
      - Fiat Transfers
    post:
      description: |-
        Create an account to initiate a fiat withdrawal.

        For U.S. wires, set `fiat_network_instructions` > `wire` > `routing_details` > `routing_number_type` to `ABA`. For international (SWIFT) wires, set `fiat_network_instructions` > `wire` > `routing_details` > `routing_number_type` to `SWIFT`.

        For CBIT, set `fiat_network_instructions` > `cbit` > `wallet_address`, and do not specify `routing_number_type`. For CBIT, the `wallet_address` on `fiat_network_instructions` is not a crypto wallet, it is a Customers Bank account wallet address.
      operationId: CreateFiatAccount
      security:
      - OAuth2:
        - transfer:write_fiat_account
      summary: Create Fiat Account
      tags:
      - Fiat Transfers
  /transfer/fiat-accounts/{id}:
    delete:
      description: |-
        Delete a Fiat Account.
        Once a Fiat Account is deleted, transfers cannot be initiated to it.
      operationId: DeleteFiatAccount
      security:
      - OAuth2:
        - transfer:write_fiat_account
      summary: Delete Fiat Account
      tags:
      - Fiat Transfers
    get:
      description: |-
        Get a single Fiat Account by ID.

        In the polling workflow, this endpoint can be called to monitor a FiatAccount's status.
        The Fiat Account response includes the full account number, beneficiary name and address details.
      operationId: GetFiatAccount
      security:
      - OAuth2:
        - transfer:read_fiat_account
      summary: Get Fiat Account
      tags:
      - Fiat Transfers
    put:
      description: |-
        Change an existing value or add a new value on one or more fields for the given Fiat Account and return the modified Fiat Account in `PENDING` status.
        Update fields in **either** `fiat_account_owner.person_details` or `fiat_account_owner.institution_details`.
        Attempts to convert the `fiat_account_owner` type results in an error.
        Empty strings or null values are ignored.

        Upon successful response, Paxos initiates an automated review of the requested changes and then either sets the status to `APPROVED` or `REJECTED`.
        Occasionally, a manual review may be required.
        Use [Get Fiat Account](#operation/GetFiatAccount) to check for status changes.
      operationId: UpdateFiatAccount
      security:
      - OAuth2:
        - transfer:write_fiat_account
      summary: Update Fiat Account
      tags:
      - Fiat Transfers
  /transfer/fiat-deposit-instructions:
    get:
      description: |-
        Return the associated Fiat Deposit Instructions matching the search criteria for the current Account.
        The paginated results default to the maximum limit of 1,000 Fiat Deposit instructions, unless otherwise specified with the `limit` parameter.
        Every paginated response contains a `next_page` field until the last page is reached.
        Pass the `next_page` value into the `page_cursor` field of the next request to retrieve the next page of results.
      operationId: ListFiatDepositInstructions
      security:
      - OAuth2:
        - transfer:read_fiat_deposit_instructions
      summary: List Fiat Deposit Instructions
      tags:
      - Fiat Transfers
    post:
      description: Create instructions for depositing fiat.
      operationId: CreateFiatDepositInstructions
      security:
      - OAuth2:
        - transfer:write_fiat_deposit_instructions
      summary: Create Fiat Deposit Instructions
      tags:
      - Fiat Transfers
  /transfer/fiat-deposit-instructions/{id}:
    get:
      description: |-
        Get instructions for depositing fiat using a Paxos Fiat Deposit Instructions ID.
        The Fiat Deposit Instructions ID (`id`) is provided in the response of the [Create Fiat Deposit Instructions](#operation/CreateFiatDepositInstructions).
      operationId: GetFiatDepositInstructions
      security:
      - OAuth2:
        - transfer:read_fiat_deposit_instructions
      summary: Get Fiat Deposit Instructions
      tags:
      - Fiat Transfers
  /transfer/fiat-withdrawals:
    post:
      description: Withdraw fiat to the given destination.
      operationId: CreateFiatWithdrawal
      security:
      - OAuth2:
        - transfer:write_fiat_withdrawal
      summary: Create Fiat Withdrawal
      tags:
      - Fiat Transfers
  /transfer/internal:
    post:
      description: Transfer assets between two profiles belonging to the same customer.
      operationId: CreateInternalTransfer
      security:
      - OAuth2:
        - transfer:write_internal_transfer
      summary: Create Internal Transfer
      tags:
      - Internal Transfers
  /transfer/limits/utilizations:
    get:
      description: List all limits that apply to the given transaction type.
      operationId: ListTransferLimits
      security:
      - OAuth2:
        - transfer:read_transfer_limit
      summary: List Transfer Limits
      tags:
      - Limits
  /transfer/transfers:
    get:
      description: |-
        List all transfers, optionally filtering and paging the results.

        By default, transfers are returned in reverse chronological (descending)
        order by creation time.

        The recommended polling workflow is to query the results in ascending
        order (by setting `order_by` to `CREATED_AT`), keeping track of the
        `created_at` timestamp of the most recent transfer in the paged results.
        Once transfers are discovered, the caller should store the returned `ID`
        and query GetTransfer to retrieve status updates.
      operationId: ListTransfers
      security:
      - OAuth2:
        - transfer:read_transfer
      summary: List Transfers
      tags:
      - Transfers
  /transfer/transfers/{id}:
    get:
      description: |-
        Get a single transfer by ID.

        In the polling workflow, this endpoint can be called to monitor transfer
        status changes.
      operationId: GetTransfer
      security:
      - OAuth2:
        - transfer:read_transfer
      summary: Get Transfer
      tags:
      - Transfers
  /tax/tax-form-revisions:
    get:
      description: |-
        Used for more granular file retrieval for specific accounts that require updated tax forms.
        Lists all versions of a tax form for single account and tax year. Revisions will increment up as new tax forms are issued for the same account, tax year, and form type pairing. The highest value revision is the most recent.
        Tax Form URL links will expire after 60 seconds.
      operationId: ListTaxFormRevisions
      security:
      - OAuth2:
        - tax:read_tax_form
      summary: List Tax Form Revisions
      tags:
      - Tax Forms
  /tax/tax-forms:
    get:
      description: |-
        Used for bulk file transfer use cases.
        List tax forms for given account ids and tax year. The most recent revision number will be returned (revisions increment up; highest value revision for a specific account, tax year, and form type pairing is the most recent).
        Tax Form URL links will expire after 60 seconds.
        Please call ListTaxFormRevisions endpoint for all versions of a single accounts tax forms.
      operationId: ListTaxForms
      security:
      - OAuth2:
        - tax:read_tax_form
      summary: List Tax Forms
      tags:
      - Tax Forms
  /tax/tax-lots:
    get:
      description: "List Tax Lots using filter, result is paginated."
      operationId: ListTaxLots
      security:
      - OAuth2:
        - tax:read_tax_lot
      summary: List Tax Lots
      tags:
      - Tax Lot
  /tax/tax-lots/{id}:
    get:
      description: Get Tax Lot allows you to retrieve tax lot detail by its id.
      operationId: GetTaxLot
      security:
      - OAuth2:
        - tax:read_tax_lot
      summary: Get Tax Lot
      tags:
      - Tax Lot
    put:
      description: Update Tax Lot allows you to update the tax lot specified by its
        ID. The updated tax lot will be returned in the response.
      operationId: UpdateTaxLot
      security:
      - OAuth2:
        - tax:write_tax_lot
      summary: Update Tax Lot
      tags:
      - Tax Lot
  /conversion/stablecoins:
    get:
      description: |-
        List all conversions, optionally filtering and paging the results.

        By default, conversions are returned in reverse chronological (descending)
        order by creation time. If no query parameters are supplied,
        the response will include up to the last 100 conversions which
        were created.

        The paginated results default to display up to 100 conversions, unless
        otherwise specified with the `limit` parameter. The maximum `limit` value is 1000.
        Every paginated response contains a `next_page_cursor` field until the last page is reached.

        Pass the `next_page_cursor` value into the `page_cursor` field of a new
        request to retrieve the next page of results.
      operationId: ListStablecoinConversions
      security:
      - OAuth2:
        - conversion:read_conversion_stablecoin
      summary: List Stablecoin Conversions
      tags:
      - Stablecoin Conversion
    post:
      description: |-
        Create a Conversion request to exchange assets 1:1.

        A request to create a conversion can fail with one of the following
        types of errors:
         - [Insufficient Funds](https://developer.paxos.com/docs/v2/problems/insufficient-funds)
           if the Profile (`profile_id`) has insufficient available balance to
           fund the execution.
         - [Already Exists](https://developer.paxos.com/docs/v2/problems/already-exists)
           if a conversion with the same external ID (`ref_id`) has already been created.
      operationId: CreateStablecoinConversion
      security:
      - OAuth2:
        - conversion:write_conversion_stablecoin
      summary: Create Stablecoin Conversion
      tags:
      - Stablecoin Conversion
  /conversion/stablecoins/{id}:
    delete:
      description: |-
        Cancel a single conversion using the `id` from the
        [Create Stablecoin Conversion](#operation/CreateStablecoinConversion) response.
      operationId: CancelStablecoinConversion
      security:
      - OAuth2:
        - conversion:write_conversion_stablecoin
      summary: Cancel Stablecoin Conversion
      tags:
      - Stablecoin Conversion
    get:
      description: "Retrieve a single conversion using the transaction `id` from the\
        \ [Create Stablecoin Conversion](#operation/CreateStablecoinConversion) response."
      operationId: GetStablecoinConversion
      security:
      - OAuth2:
        - conversion:read_conversion_stablecoin
      summary: Get Stablecoin Conversion
      tags:
      - Stablecoin Conversion
  /settlement/transactions:
    get:
      description: |-
        This endpoint enables you to fetch a list of Settlement Transactions that you have created (own the `source_profile_id`) or have been alleged against you (own the `target_profile_id`).
        You can use query parameters to filter the results returned by `statuses`, `source_profile_id` and `target_profile_id`.

        Note that this endpoint supports pagination and returns a cursor token for fetching next pages.
      operationId: ListTransactions
      security:
      - OAuth2:
        - settlement:read_transaction
      summary: List Transactions
      tags:
      - Settlement
    post:
      description: |-
        Creates a new bilateral Settlement Transaction with one or more legs. The customer must own the
        `source_profile_id` specified in the transaction.

        A successful response indicates the transaction has been accepted and will be in an initial `status` of `"PENDING"`
        for settlement, the transaction is only eligible for settlement once the `status` is `"AFFIRMED"` by the
        `target_profile_id` and the current time is between the provided `settlement_window_start` and `settlement_window_end`.

        Settlement will only be enacted once both `source_profile_id` and `target_profile_id` have sufficient balances to
        fulfill all legs specified as settlement is **atomic**.
      operationId: CreateTransaction
      security:
      - OAuth2:
        - settlement:write_transaction
      summary: Create Transaction
      tags:
      - Settlement
  /settlement/transactions/{transaction_id}:
    delete:
      description: |-
        Cancels the Settlement Transaction, this action can only be done by the customer owning the source profile (`source_profile_id`).
        The transaction must be in a `"PENDING"` status for this to take effect, you cannot cancel a transaction which
        is `"AFFIRMED"`.
      operationId: CancelTransaction
      security:
      - OAuth2:
        - settlement:write_transaction
      summary: Cancel Transaction
      tags:
      - Settlement
    get:
      description: |-
        Get a Settlement Transaction by its (transaction) id, you must have created the transaction (own the `source_profile_id`) or
        have had the transaction alleged against you (own the `target_profile_id`).
      operationId: GetTransaction
      security:
      - OAuth2:
        - settlement:read_transaction
      summary: Get Transaction
      tags:
      - Settlement
  /settlement/transactions/{transaction_id}/affirm:
    put:
      description: |-
        Affirms the Settlement Transaction for settlement, the transaction is now eligible for settlement once the current time is
        between the provided `settlement_window_start` and `settlement_window_end`. This action can only be done by the
        customer owning the target profile (`target_profile_id`).
        The transaction must be in a `"PENDING"` status for this to take effect.
      operationId: AffirmTransaction
      security:
      - OAuth2:
        - settlement:write_transaction
      summary: Affirm Transaction
      tags:
      - Settlement
components:
  securitySchemes:
    OAuth2:
      description: |
        The Paxos API uses OAuth2.

        All API access is restricted by OAuth2 **scopes**.
        Credentials are created with a set of granted scopes and can only access endpoints permitted for those scopes.

        Every endpoint that requires a scope must be accompanied by an <b>"Authorization"</b> header with a value that follows the following schema: <b>"Bearer ACCESS_TOKEN"</b>

        We have a <a href="https://developer.paxos.com/docs/Paxos_Sandbox_V2_Oauth_Guide.pdf" target="_blank">guide</a> on how to create API credentials and gain an access token to our sandbox environment.
      flows:
        clientCredentials:
          scopes:
            funding:read_profile: Read profile and balance data
            exchange:read_quote: Read quotes and quote history
            exchange:write_quote_execution: Execute on quoted prices
            exchange:read_quote_execution: Read quote executions
            exchange:write_order: Create and Cancel Orders
            exchange:read_order: Read Orders and Executions
            exchange:historical_prices: Read Historical Pricing Data
            transfer:read_transfer: Read deposit and withdrawal transfers
            transfer:read_deposit_address: Read deposit addresses
            transfer:write_deposit_address: Create and manage deposit addresses
            fee:write_crypto_withdrawal_fee: Create crypto withdrawal fees
            transfer:write_crypto_withdrawal: Create crypto withdrawal transfers
            conversion:read_conversion_stablecoin: Retrieve requested or completed
              conversions
            conversion:write_conversion_stablecoin: Create or cancel a conversion
              request
          tokenUrl: https://oauth.paxos.com/oauth2/token
      type: oauth2
x-tagGroups:
- name: Profiles
  tags:
  - Profiles
- name: Trading
  tags:
  - Market Data
  - Orders
  - Quotes
  - Quote Executions
  - Pricing
- name: Settlements
  tags:
  - Settlement
- name: Stablecoin Conversion
  tags:
  - Stablecoin Conversion
- name: Identity
  tags:
  - Identity
  - Institution Members
  - Identity Credentials
  - Accounts
  - Account Members
  - Identity Documents
- name: Sandbox
  tags:
  - Sandbox Deposits
  - Sandbox Identity
  - Sandbox Fiat Transfers
- name: Deposits and Withdrawals
  tags:
  - Transfers
  - Fiat Transfers
  - Deposit Addresses
  - Crypto Deposits
  - Crypto Withdrawals
  - Fees
  - Internal Transfers
  - Limits
- name: Taxes
  tags:
  - Tax Forms
